# Generated by Django 5.2.14 on 2026-05-27 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUserPermission',
            fields=[
                ('id_permission', models.BigAutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('platform_dashboard', 'CRM Admin Dashboard'), ('companies', 'Companies'), ('platform_plans', 'Platform Plans'), ('platform_subscriptions', 'Subscriptions'), ('platform_documents', 'Platform Documents'), ('platform_payments', 'Platform Payments'), ('platform_calendar', 'Platform Calendar'), ('platform_email', 'Platform Email'), ('platform_notifications', 'Platform Notifications'), ('platform_audit', 'Platform Audit'), ('dashboard_metrics', 'Resources Dashboard'), ('system_monitor', 'System Monitor')], db_index=True, max_length=100)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='platform_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_user_permission',
                'ordering': ['module'],
                'indexes': [models.Index(fields=['module'], name='plat_user_perm_module_idx')],
                'unique_together': {('id_user', 'module')},
            },
        ),
    ]
