SUBSCRIPTION_TRIAL = "trial"
SUBSCRIPTION_ACTIVE = "active"
SUBSCRIPTION_EXPIRED = "expired"
SUBSCRIPTION_SUSPENDED = "suspended"
SUBSCRIPTION_CANCELED = "canceled"

SUBSCRIPTION_STATUS_CHOICES = [
    (SUBSCRIPTION_TRIAL, "Trial"),
    (SUBSCRIPTION_ACTIVE, "Active"),
    (SUBSCRIPTION_EXPIRED, "Expired"),
    (SUBSCRIPTION_SUSPENDED, "Suspended"),
    (SUBSCRIPTION_CANCELED, "Canceled"),
]