# Generated by Django 5.2.14 on 2026-05-19 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id_supervision', models.BigAutoField(primary_key=True, serialize=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('final_audit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='supervisions', to='projects.project')),
                ('id_supervisor', models.ForeignKey(db_column='id_supervisor', on_delete=django.db.models.deletion.CASCADE, related_name='supervisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supervision',
                'ordering': ['-created_at'],
            },
        ),
    ]
