# Generated by Django 5.2.14 on 2026-05-19 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id_inspection', models.BigAutoField(primary_key=True, serialize=False)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('materials', models.TextField(blank=True, null=True)),
                ('photos', models.TextField(blank=True, null=True)),
                ('estimated_time', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('id_inspector', models.ForeignKey(db_column='id_inspector', on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('id_project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='projects.project')),
            ],
            options={
                'db_table': 'inspection',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
