# Generated by Django 5.2.15 on 2026-06-11 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_code_client_first_name_and_more'),
        ('employees', '0002_alter_employee_options_alter_employee_hourly_rate_and_more'),
        ('inspections', '0002_alter_inspection_options_inspection_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionAssignment',
            fields=[
                ('id_assignment', models.BigAutoField(primary_key=True, serialize=False)),
                ('inspection_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='inspection_assignments', to='clients.client')),
                ('inspector', models.ForeignKey(blank=True, db_column='id_inspector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_assignments', to='employees.employee')),
            ],
            options={
                'db_table': 'inspection_assignment',
                'ordering': ['-inspection_date', '-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='insp_assign_client_status_idx'), models.Index(fields=['inspector', 'status'], name='insp_asg_inspector_idx'), models.Index(fields=['inspection_date'], name='insp_assign_date_idx')],
            },
        ),
    ]
