# Generated by Django 5.2.15 on 2026-06-11 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_inspectionassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionassignment',
            name='inspector',
            field=models.ForeignKey(blank=True, db_column='id_inspector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
