# Generated by Django 5.2.15 on 2026-06-12 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_inspectionassignment_inspector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='inspectionassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='InspectionAssignmentGalleryImage',
            fields=[
                ('id_image', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('before', 'Before'), ('during', 'During'), ('after', 'After')], default='before', max_length=20)),
                ('file', models.ImageField(upload_to='inspection_assignments/gallery/')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(db_column='id_assignment', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='inspections.inspectionassignment')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_assignment_gallery_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspection_assignment_gallery_image',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
