# Generated by Django 5.2.15 on 2026-06-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_alter_inspection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionassignment',
            name='inspection_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
