from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import NoReverseMatch, reverse, reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from rest_framework.exceptions import PermissionDenied

from apps.core.mixins import TenantModelViewSet
from apps.core.template_permissions import (
    ModulePermissionRequiredMixin,
    PERMISSION_CREATE,
    PERMISSION_EDIT,
    PERMISSION_VIEW,
    user_can_module_action,
)

from .forms import NotificationForm
from .models import Notification
from .permissions import user_can_access_notification
from .selectors import notification_list_for_user
from .serializers import NotificationSerializer
from .services import (
    mark_all_user_notifications_read,
    notification_archive,
    notification_mark_read,
    notification_mark_unread,
)


def get_notification_company_slug(request=None, kwargs=None):
    kwargs = kwargs or {}

    if kwargs.get("company_slug"):
        return kwargs.get("company_slug")

    current_company = getattr(request, "current_company", None) if request else None

    if current_company and getattr(current_company, "slug", None):
        return current_company.slug

    user = getattr(request, "user", None) if request else None
    user_company = getattr(user, "id_company", None) if user else None

    if user_company and getattr(user_company, "slug", None):
        return user_company.slug

    return None


def notification_reverse(name, request=None, kwargs=None, **extra_kwargs):
    url_kwargs = {}
    company_slug = get_notification_company_slug(request=request, kwargs=kwargs)

    if company_slug:
        url_kwargs["company_slug"] = company_slug

    url_kwargs.update(extra_kwargs)

    try:
        return reverse(f"notifications:{name}", kwargs=url_kwargs)
    except NoReverseMatch:
        url_kwargs.pop("company_slug", None)
        return reverse(f"notifications:{name}", kwargs=url_kwargs)


class NotificationListView(LoginRequiredMixin, ModulePermissionRequiredMixin, ListView):
    module_name = "notifications"
    permission_required = PERMISSION_VIEW
    template_name = "notifications/list.html"
    context_object_name = "notifications"
    paginate_by = 20
    login_url = "/login/"

    def get_queryset(self):
        return notification_list_for_user(self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["page_title"] = "Notifications"
        context["company_slug"] = get_notification_company_slug(
            request=self.request,
            kwargs=self.kwargs,
        )

        context["can_view_notifications"] = user_can_module_action(
            self.request.user,
            "notifications",
            PERMISSION_VIEW,
        )

        # Company users should not manually create or edit notifications.
        # Notifications are generated by platform workflows.
        context["can_create_notifications"] = False
        context["can_edit_notifications"] = False

        return context


class NotificationDetailView(LoginRequiredMixin, ModulePermissionRequiredMixin, DetailView):
    module_name = "notifications"
    permission_required = PERMISSION_VIEW
    model = Notification
    template_name = "notifications/detail.html"
    context_object_name = "notification"
    pk_url_kwarg = "id_notification"
    login_url = "/login/"

    def get_queryset(self):
        return notification_list_for_user(self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        company_slug = get_notification_company_slug(
            request=self.request,
            kwargs=self.kwargs,
        )

        context["page_title"] = "Notification Details"
        context["company_slug"] = company_slug

        context["notification_list_url"] = notification_reverse(
            "notification_list",
            request=self.request,
            kwargs=self.kwargs,
        )

        context["notification_mark_read_url"] = notification_reverse(
            "notification_mark_read",
            request=self.request,
            kwargs=self.kwargs,
            id_notification=self.object.id_notification,
        )

        context["notification_mark_unread_url"] = notification_reverse(
            "notification_mark_unread",
            request=self.request,
            kwargs=self.kwargs,
            id_notification=self.object.id_notification,
        )

        context["notification_archive_url"] = notification_reverse(
            "notification_archive",
            request=self.request,
            kwargs=self.kwargs,
            id_notification=self.object.id_notification,
        )

        return context


class NotificationCreateView(LoginRequiredMixin, ModulePermissionRequiredMixin, CreateView):
    module_name = "notifications"
    permission_required = PERMISSION_CREATE
    model = Notification
    form_class = NotificationForm
    template_name = "notifications/form.html"
    success_url = reverse_lazy("notifications:notification_list")
    login_url = "/login/"

    def dispatch(self, request, *args, **kwargs):
        return HttpResponseForbidden(
            "Manual notification creation is disabled for company workspaces."
        )


class NotificationUpdateView(LoginRequiredMixin, ModulePermissionRequiredMixin, UpdateView):
    module_name = "notifications"
    permission_required = PERMISSION_EDIT
    model = Notification
    form_class = NotificationForm
    template_name = "notifications/form.html"
    context_object_name = "notification"
    pk_url_kwarg = "id_notification"
    login_url = "/login/"

    def dispatch(self, request, *args, **kwargs):
        return HttpResponseForbidden(
            "Manual notification editing is disabled for company workspaces."
        )

@require_POST
def notification_mark_all_read_view(request, company_slug=None):
    updated_count = mark_all_user_notifications_read(request.user)

    if updated_count:
        messages.success(request, f"{updated_count} notification(s) marked as read.")
    else:
        messages.info(request, "No unread notifications found.")

    return redirect(
        notification_reverse(
            "notification_list",
            request=request,
            kwargs={"company_slug": company_slug},
        )
    )

@require_POST
def notification_mark_read_view(request, id_notification, company_slug=None):
    notification = get_object_or_404(
        notification_list_for_user(request.user),
        id_notification=id_notification,
    )

    if not user_can_access_notification(request.user, notification):
        return HttpResponseForbidden("Permission denied.")

    notification_mark_read(notification)
    messages.success(request, "Notification marked as read.")

    return redirect(
        notification_reverse(
            "notification_detail",
            request=request,
            kwargs={"company_slug": company_slug},
            id_notification=notification.id_notification,
        )
    )


@require_POST
def notification_mark_unread_view(request, id_notification, company_slug=None):
    notification = get_object_or_404(
        notification_list_for_user(request.user),
        id_notification=id_notification,
    )

    if not user_can_access_notification(request.user, notification):
        return HttpResponseForbidden("Permission denied.")

    notification_mark_unread(notification)
    messages.success(request, "Notification marked as unread.")

    return redirect(
        notification_reverse(
            "notification_detail",
            request=request,
            kwargs={"company_slug": company_slug},
            id_notification=notification.id_notification,
        )
    )


@require_POST
def notification_archive_view(request, id_notification, company_slug=None):
    notification = get_object_or_404(
        notification_list_for_user(request.user),
        id_notification=id_notification,
    )

    if not user_can_access_notification(request.user, notification):
        return HttpResponseForbidden("Permission denied.")

    notification_archive(notification)
    messages.success(request, "Notification archived.")

    return redirect(
        notification_reverse(
            "notification_list",
            request=request,
            kwargs={"company_slug": company_slug},
        )
    )


class NotificationViewSet(TenantModelViewSet):
    module_name = "notifications"
    queryset = Notification.objects.select_related(
        "id_user",
        "id_user__id_company",
        "id_user__id_role",
    ).all()
    serializer_class = NotificationSerializer
    tenant_filter_path = None
    tenant_create_field = None

    def get_queryset(self):
        return notification_list_for_user(self.request.user)

    def perform_create(self, serializer):
        target_user = serializer.validated_data.get("id_user")

        if not self.request.user.is_superuser:
            if not target_user or target_user.id_company_id != self.request.user.id_company_id:
                raise PermissionDenied("You can only create notifications for users in your company.")

        serializer.save()

    def perform_update(self, serializer):
        target_user = serializer.validated_data.get("id_user")

        if not self.request.user.is_superuser:
            if target_user and target_user.id_company_id != self.request.user.id_company_id:
                raise PermissionDenied("You can only update notifications for users in your company.")

        serializer.save()