# Generated by ChatGPT fix package

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimates", "0002_estimateitem_estimate_client_billing_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="pdf_header_dark",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="estimateitem",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="estimates/items/"),
        ),
    ]
