# Generated by ChatGPT fix package

import uuid

from django.db import migrations, models
from django.utils import timezone


def populate_public_tokens(apps, schema_editor):
    Estimate = apps.get_model("estimates", "Estimate")

    for estimate in Estimate.objects.filter(public_token__isnull=True):
        estimate.public_token = uuid.uuid4()
        estimate.public_token_refreshed_at = timezone.now()
        estimate.save(update_fields=["public_token", "public_token_refreshed_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("estimates", "0003_estimate_pdf_header_dark_estimateitem_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="public_token",
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="public_token_refreshed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(populate_public_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="estimate",
            name="public_token",
            field=models.UUIDField(default=uuid.uuid4, db_index=True, editable=False, unique=True),
        ),
    ]
