# Generated by Django 5.2.14 on 2026-05-21 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModule',
            fields=[
                ('id_company_module', models.BigAutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('companies', 'Companies'), ('roles', 'Roles'), ('users', 'Users'), ('employees', 'Employees'), ('notifications', 'Notifications'), ('system_logs', 'System Logs'), ('clients', 'Clients'), ('leads', 'Leads'), ('projects', 'Projects'), ('inspections', 'Inspections'), ('estimates', 'Estimates'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('contracts', 'Contracts'), ('evidence', 'Evidence'), ('supervision', 'Supervision'), ('calendar', 'Calendar'), ('notifications', 'Notifications'), ('clients', 'Clients'), ('leads', 'Leads'), ('projects', 'Projects'), ('inspections', 'Inspections'), ('evidence', 'Evidence'), ('supervision', 'Supervision'), ('calendar_events', 'Calendar Events'), ('estimates', 'Estimates'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('contracts', 'Contracts'), ('reports', 'Reports'), ('system_logs', 'System Logs')], max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='company_modules', to='companies.company')),
            ],
            options={
                'db_table': 'company_module',
                'ordering': ['id_company__name', 'module'],
                'unique_together': {('id_company', 'module')},
            },
        ),
    ]
