# Generated by Django 5.2.15 on 2026-06-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_modules', '0002_alter_companymodule_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodule',
            name='module',
            field=models.CharField(choices=[('companies', 'Companies'), ('roles', 'Roles'), ('users', 'Users'), ('employees', 'Employees'), ('notifications', 'Notifications'), ('system_logs', 'System Logs'), ('clients', 'Clients'), ('leads', 'Leads'), ('opportunities', 'Opportunities'), ('projects', 'Projects'), ('inspections', 'Inspections'), ('estimates', 'Estimates'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('contracts', 'Contracts'), ('evidence', 'Evidence'), ('supervision', 'Supervision'), ('calendar_events', 'Calendar Events'), ('reports', 'Reports'), ('smtp_settings', 'SMTP Settings'), ('company_modules', 'Company Modules'), ('platform_dashboard', 'Platform Dashboard'), ('platform_companies', 'Platform Companies'), ('platform_plans', 'Platform Plans'), ('platform_subscriptions', 'Platform Subscriptions'), ('platform_documents', 'Platform Documents'), ('platform_payments', 'Platform Payments'), ('platform_calendar', 'Platform Calendar'), ('platform_email', 'Platform Email'), ('platform_notifications', 'Platform Notifications'), ('platform_audit', 'Platform Audit'), ('platform_metrics', 'Platform Metrics'), ('platform_system_monitor', 'Platform System Monitor')], max_length=100),
        ),
    ]
