INSPECTION_STATUS_DRAFT = "draft"
INSPECTION_STATUS_PENDING = "pending"
INSPECTION_STATUS_IN_PROGRESS = "in_progress"
INSPECTION_STATUS_REVIEW = "review"
INSPECTION_STATUS_COMPLETED = "completed"
INSPECTION_STATUS_CANCELLED = "cancelled"

INSPECTION_STATUS_CHOICES = [
    (INSPECTION_STATUS_DRAFT, "Draft"),
    (INSPECTION_STATUS_PENDING, "Pending"),
    (INSPECTION_STATUS_IN_PROGRESS, "In Progress"),
    (INSPECTION_STATUS_REVIEW, "Under Review"),
    (INSPECTION_STATUS_COMPLETED, "Approved"),
    (INSPECTION_STATUS_CANCELLED, "Void"),
]

# Inspection assignments use the same canonical workflow.
INSPECTION_ASSIGNMENT_STATUS_DRAFT = INSPECTION_STATUS_DRAFT
INSPECTION_ASSIGNMENT_STATUS_PENDING = INSPECTION_STATUS_PENDING
INSPECTION_ASSIGNMENT_STATUS_IN_PROGRESS = INSPECTION_STATUS_IN_PROGRESS
INSPECTION_ASSIGNMENT_STATUS_REVIEW = INSPECTION_STATUS_REVIEW
INSPECTION_ASSIGNMENT_STATUS_COMPLETED = INSPECTION_STATUS_COMPLETED
INSPECTION_ASSIGNMENT_STATUS_CANCELLED = INSPECTION_STATUS_CANCELLED

INSPECTION_ASSIGNMENT_STATUS_CHOICES = INSPECTION_STATUS_CHOICES

INSPECTION_MANUAL_STATUS_VALUES = {
    INSPECTION_STATUS_DRAFT,
    INSPECTION_STATUS_PENDING,
    INSPECTION_STATUS_IN_PROGRESS,
}
INSPECTION_LOCKED_STATUS_VALUES = {
    INSPECTION_STATUS_REVIEW,
    INSPECTION_STATUS_COMPLETED,
    INSPECTION_STATUS_CANCELLED,
}
