CONTRACT_STATUS_DRAFT = "draft"
CONTRACT_STATUS_GENERATED = "generated"
CONTRACT_STATUS_SENT = "sent"
CONTRACT_STATUS_VIEWED = "viewed"
CONTRACT_STATUS_APPROVED = "approved"
CONTRACT_STATUS_SIGNED = "signed"
CONTRACT_STATUS_REJECTED = "rejected"
CONTRACT_STATUS_VOID = "void"

# Legacy compatibility
CONTRACT_STATUS_PENDING = "pending"
CONTRACT_STATUS_ACTIVE = "active"
CONTRACT_STATUS_COMPLETED = "completed"
CONTRACT_STATUS_CANCELLED = "cancelled"


CONTRACT_STATUS_CHOICES = [
    (CONTRACT_STATUS_DRAFT, "Draft"),
    (CONTRACT_STATUS_GENERATED, "Generated"),
    (CONTRACT_STATUS_SENT, "Sent"),
    (CONTRACT_STATUS_VIEWED, "Viewed"),
    (CONTRACT_STATUS_APPROVED, "Approved"),
    (CONTRACT_STATUS_SIGNED, "Signed"),
    (CONTRACT_STATUS_REJECTED, "Rejected"),
    (CONTRACT_STATUS_VOID, "Void"),

    # Legacy compatibility
    (CONTRACT_STATUS_PENDING, "Pending"),
    (CONTRACT_STATUS_ACTIVE, "Active"),
    (CONTRACT_STATUS_COMPLETED, "Completed"),
    (CONTRACT_STATUS_CANCELLED, "Cancelled"),
]


CONTRACT_EDITABLE_STATUSES = [
    CONTRACT_STATUS_DRAFT,
    CONTRACT_STATUS_PENDING,
    CONTRACT_STATUS_GENERATED,
]


CONTRACT_SENDABLE_STATUSES = [
    CONTRACT_STATUS_GENERATED,
    CONTRACT_STATUS_SENT,
    CONTRACT_STATUS_VIEWED,
    CONTRACT_STATUS_APPROVED,
]

CONTRACT_VOIDABLE_STATUSES = [
    CONTRACT_STATUS_GENERATED,
    CONTRACT_STATUS_SENT,
    CONTRACT_STATUS_VIEWED,
    CONTRACT_STATUS_APPROVED,
]


CONTRACT_DECISION_ALLOWED_STATUSES = [
    CONTRACT_STATUS_SENT,
    CONTRACT_STATUS_VIEWED,
]


CONTRACT_SIGNABLE_STATUSES = [
    CONTRACT_STATUS_SENT,
    CONTRACT_STATUS_VIEWED,
    CONTRACT_STATUS_APPROVED,
]


CONTRACT_FINAL_STATUSES = [
    CONTRACT_STATUS_SIGNED,
    CONTRACT_STATUS_REJECTED,
    CONTRACT_STATUS_VOID,
    CONTRACT_STATUS_CANCELLED,
    CONTRACT_STATUS_COMPLETED,
]