PAYMENT_STATUS_PENDING_PAYMENT = "pending_payment"
PAYMENT_STATUS_PAID = "paid"
PAYMENT_STATUS_VERIFIED = "verified"
PAYMENT_STATUS_REJECTED = "rejected"
PAYMENT_STATUS_CANCELLED = "cancelled"

# Final accounting status.
PAYMENT_STATUS_CONFIRMED = "confirmed"
PAYMENT_STATUS_VOID = "void"


PAYMENT_STATUS_CHOICES = [
    (PAYMENT_STATUS_PENDING_PAYMENT, "Pending Payment"),
    (PAYMENT_STATUS_PAID, "Paid"),
    (PAYMENT_STATUS_VERIFIED, "Verified"),
    (PAYMENT_STATUS_CONFIRMED, "Confirmed"),
    (PAYMENT_STATUS_REJECTED, "Rejected"),
    (PAYMENT_STATUS_CANCELLED, "Cancelled"),
    (PAYMENT_STATUS_VOID, "Void"),
]


PAYMENT_ACTIVE_STATUSES = [
    PAYMENT_STATUS_PENDING_PAYMENT,
    PAYMENT_STATUS_PAID,
    PAYMENT_STATUS_VERIFIED,
    PAYMENT_STATUS_CONFIRMED,
]


PAYMENT_CONFIRMED_STATUSES = [
    PAYMENT_STATUS_PAID,
    PAYMENT_STATUS_VERIFIED,
    PAYMENT_STATUS_CONFIRMED,
]


PAYMENT_VOID_STATUSES = [
    PAYMENT_STATUS_REJECTED,
    PAYMENT_STATUS_CANCELLED,
    PAYMENT_STATUS_VOID,
]


PAYMENT_METHOD_CASH = "cash"
PAYMENT_METHOD_CHECK = "check"
PAYMENT_METHOD_BANK_TRANSFER = "bank_transfer"
PAYMENT_METHOD_ZELLE = "zelle"
PAYMENT_METHOD_ACH = "ach"
PAYMENT_METHOD_CREDIT_CARD = "credit_card"
PAYMENT_METHOD_PAYPAL = "paypal"
PAYMENT_METHOD_OTHER = "other"


PAYMENT_METHOD_CHOICES = [
    (PAYMENT_METHOD_CASH, "Cash"),
    (PAYMENT_METHOD_CHECK, "Check"),
    (PAYMENT_METHOD_BANK_TRANSFER, "Bank Transfer"),
    (PAYMENT_METHOD_ZELLE, "Zelle"),
    (PAYMENT_METHOD_ACH, "ACH"),
    (PAYMENT_METHOD_CREDIT_CARD, "Credit Card"),
    (PAYMENT_METHOD_PAYPAL, "PayPal"),
    (PAYMENT_METHOD_OTHER, "Other"),
]


FINANCIAL_MOVEMENT_INVOICE = "invoice"
FINANCIAL_MOVEMENT_PAYMENT = "payment"
FINANCIAL_MOVEMENT_VOID = "void"
FINANCIAL_MOVEMENT_PAYMENT_VOID = "payment_void"
FINANCIAL_MOVEMENT_CREDIT_CREATED = "credit_created"
FINANCIAL_MOVEMENT_CREDIT_APPLIED = "credit_applied"
FINANCIAL_MOVEMENT_CREDIT_VOID = "credit_void"


FINANCIAL_MOVEMENT_TYPE_CHOICES = [
    (FINANCIAL_MOVEMENT_INVOICE, "Invoice"),
    (FINANCIAL_MOVEMENT_PAYMENT, "Payment"),
    (FINANCIAL_MOVEMENT_VOID, "Invoice Void"),
    (FINANCIAL_MOVEMENT_PAYMENT_VOID, "Payment Void"),
    (FINANCIAL_MOVEMENT_CREDIT_CREATED, "Credit Created"),
    (FINANCIAL_MOVEMENT_CREDIT_APPLIED, "Credit Applied"),
    (FINANCIAL_MOVEMENT_CREDIT_VOID, "Credit Void"),
]


CREDIT_MOVEMENT_CREATED = "created"
CREDIT_MOVEMENT_APPLIED = "applied"
CREDIT_MOVEMENT_VOIDED = "voided"
CREDIT_MOVEMENT_ADJUSTMENT = "adjustment"


CREDIT_MOVEMENT_TYPE_CHOICES = [
    (CREDIT_MOVEMENT_CREATED, "Credit Created"),
    (CREDIT_MOVEMENT_APPLIED, "Credit Applied"),
    (CREDIT_MOVEMENT_VOIDED, "Credit Voided"),
    (CREDIT_MOVEMENT_ADJUSTMENT, "Credit Adjustment"),
]