# Generated by Django 5.2.14 on 2026-05-19 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
                ('id_inspector', models.ForeignKey(blank=True, db_column='id_inspector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id_assignment', models.BigAutoField(primary_key=True, serialize=False)),
                ('task', models.TextField(blank=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='assigned', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('id_employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='employees.employee')),
                ('id_project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project')),
            ],
            options={
                'db_table': 'project_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
