# Generated by Django 5.2.15 on 2026-06-10 21:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_code_client_first_name_and_more'),
        ('companies', '0006_remove_company_website'),
        ('opportunities', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvidence',
            fields=[
                ('id_project_evidence', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='project_evidence/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id_project_gallery_image', models.BigAutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('before', 'Before'), ('during', 'During'), ('after', 'After')], max_length=20)),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_gallery_image',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id_project_note', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='id_opportunity',
            field=models.ForeignKey(blank=True, db_column='id_opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='opportunities.lead'),
        ),
        migrations.AddField(
            model_name='project',
            name='invoice_status',
            field=models.CharField(choices=[('no_invoice', 'No Invoice'), ('invoice_attached', 'Invoice Attached')], default='no_invoice', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='project_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['id_company', 'id_client'], name='project_company_client_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_code'], name='project_code_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='project_status_idx'),
        ),
        migrations.AddField(
            model_name='projectevidence',
            name='id_project',
            field=models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectevidence',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_evidence_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgalleryimage',
            name='project',
            field=models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='id_project',
            field=models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project'),
        ),
    ]
