# Generated by Django 5.2.15 on 2026-06-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projectassignment_id_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
