EVENT_STATUS_SCHEDULED = "scheduled"
EVENT_STATUS_IN_PROGRESS = "in_progress"
EVENT_STATUS_COMPLETED = "completed"
EVENT_STATUS_CANCELLED = "cancelled"

EVENT_STATUS_CHOICES = [
    (EVENT_STATUS_SCHEDULED, "Scheduled"),
    (EVENT_STATUS_IN_PROGRESS, "In Progress"),
    (EVENT_STATUS_COMPLETED, "Completed"),
    (EVENT_STATUS_CANCELLED, "Cancelled"),
]

EVENT_CATEGORY_TASK = "task"
EVENT_CATEGORY_APPOINTMENT = "appointment"
EVENT_CATEGORY_MEETING = "meeting"
EVENT_CATEGORY_CALL = "call"
EVENT_CATEGORY_FOLLOW_UP = "follow_up"
EVENT_CATEGORY_DEADLINE = "deadline"
EVENT_CATEGORY_REMINDER = "reminder"
EVENT_CATEGORY_OTHER = "other"

EVENT_CATEGORY_CHOICES = [
    (EVENT_CATEGORY_TASK, "Task"),
    (EVENT_CATEGORY_APPOINTMENT, "Appointment"),
    (EVENT_CATEGORY_MEETING, "Meeting"),
    (EVENT_CATEGORY_CALL, "Call"),
    (EVENT_CATEGORY_FOLLOW_UP, "Follow-up"),
    (EVENT_CATEGORY_DEADLINE, "Deadline"),
    (EVENT_CATEGORY_REMINDER, "Reminder"),
    (EVENT_CATEGORY_OTHER, "Other"),
]

EVENT_PRIORITY_LOW = "low"
EVENT_PRIORITY_NORMAL = "normal"
EVENT_PRIORITY_HIGH = "high"
EVENT_PRIORITY_URGENT = "urgent"

EVENT_PRIORITY_CHOICES = [
    (EVENT_PRIORITY_LOW, "Low"),
    (EVENT_PRIORITY_NORMAL, "Normal"),
    (EVENT_PRIORITY_HIGH, "High"),
    (EVENT_PRIORITY_URGENT, "Urgent"),
]

RELATED_TYPE_NONE = ""
RELATED_TYPE_PROJECT = "project"
RELATED_TYPE_INSPECTION = "inspection"
RELATED_TYPE_ESTIMATE = "estimate"
RELATED_TYPE_INVOICE = "invoice"
RELATED_TYPE_PAYMENT = "payment"
RELATED_TYPE_CLIENT = "client"
RELATED_TYPE_OPPORTUNITY = "opportunity"

RELATED_TYPE_CHOICES = [
    (RELATED_TYPE_NONE, "No linked record"),
    (RELATED_TYPE_PROJECT, "Project"),
    (RELATED_TYPE_INSPECTION, "Inspection"),
    (RELATED_TYPE_ESTIMATE, "Estimate"),
    (RELATED_TYPE_INVOICE, "Invoice"),
    (RELATED_TYPE_PAYMENT, "Payment"),
    (RELATED_TYPE_CLIENT, "Client"),
    (RELATED_TYPE_OPPORTUNITY, "Opportunity"),
]
