# Generated by Django 5.2.14 on 2026-05-19 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id_event', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='scheduled', max_length=50)),
                ('id_assigned_user', models.ForeignKey(blank=True, db_column='id_assigned_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='companies.company')),
                ('id_project', models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='projects.project')),
            ],
            options={
                'db_table': 'calendar_event',
                'ordering': ['event_date', 'start_time'],
            },
        ),
    ]
