# Generated by Django 5.2.14 on 2026-05-26 22:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_slug_company_company_slug_idx'),
        ('platform_documents', '0001_initial'),
        ('platform_subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPayment',
            fields=[
                ('id_payment', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_number', models.CharField(db_index=True, max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('void', 'Void')], db_index=True, default='pending', max_length=30)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('bank_transfer', 'Bank Transfer'), ('zelle', 'Zelle'), ('card', 'Card'), ('cash', 'Cash'), ('other', 'Other')], db_index=True, default='manual', max_length=40)),
                ('reference', models.CharField(blank=True, max_length=180, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='platform_payments', to='companies.company')),
                ('id_document', models.ForeignKey(blank=True, db_column='id_document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_payments', to='platform_documents.platformdocument')),
                ('id_subscription', models.ForeignKey(blank=True, db_column='id_subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_payments', to='platform_subscriptions.platformsubscription')),
                ('received_by', models.ForeignKey(blank=True, db_column='received_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_platform_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_payment',
                'ordering': ['-payment_date', '-id_payment'],
                'indexes': [models.Index(fields=['payment_number'], name='platform_pay_number_idx'), models.Index(fields=['status'], name='platform_pay_status_idx'), models.Index(fields=['method'], name='platform_pay_method_idx'), models.Index(fields=['payment_date'], name='platform_pay_date_idx')],
            },
        ),
    ]
