NOTIFICATION_TYPE_RENEWAL_REMINDER = "renewal_reminder"
NOTIFICATION_TYPE_SUBSCRIPTION_EXPIRED = "subscription_expired"
NOTIFICATION_TYPE_PAYMENT_REGISTERED = "payment_registered"
NOTIFICATION_TYPE_DOCUMENT_SENT = "document_sent"
NOTIFICATION_TYPE_COMPANY_SUSPENDED = "company_suspended"
NOTIFICATION_TYPE_MANUAL = "manual"

NOTIFICATION_TYPE_CHOICES = [
    (NOTIFICATION_TYPE_RENEWAL_REMINDER, "Renewal Reminder"),
    (NOTIFICATION_TYPE_SUBSCRIPTION_EXPIRED, "Subscription Expired"),
    (NOTIFICATION_TYPE_PAYMENT_REGISTERED, "Payment Registered"),
    (NOTIFICATION_TYPE_DOCUMENT_SENT, "Document Sent"),
    (NOTIFICATION_TYPE_COMPANY_SUSPENDED, "Company Suspended"),
    (NOTIFICATION_TYPE_MANUAL, "Manual"),
]

NOTIFICATION_CHANNEL_EMAIL = "email"

NOTIFICATION_CHANNEL_CHOICES = [
    (NOTIFICATION_CHANNEL_EMAIL, "Email"),
]

NOTIFICATION_STATUS_PENDING = "pending"
NOTIFICATION_STATUS_SENT = "sent"
NOTIFICATION_STATUS_FAILED = "failed"
NOTIFICATION_STATUS_SKIPPED = "skipped"

NOTIFICATION_STATUS_CHOICES = [
    (NOTIFICATION_STATUS_PENDING, "Pending"),
    (NOTIFICATION_STATUS_SENT, "Sent"),
    (NOTIFICATION_STATUS_FAILED, "Failed"),
    (NOTIFICATION_STATUS_SKIPPED, "Skipped"),
]