INVOICE_STATUS_DRAFT = "draft"
INVOICE_STATUS_PENDING_SEND = "pending_send"
INVOICE_STATUS_SENT = "sent"
INVOICE_STATUS_VOID = "void"

# Legacy constants kept only for imports, old records and compatibility.
# Do not use these in the new invoice workflow.
INVOICE_STATUS_PENDING = "pending"
INVOICE_STATUS_PARTIALLY_PAID = "partially_paid"
INVOICE_STATUS_PAID = "paid"
INVOICE_STATUS_OVERDUE = "overdue"
INVOICE_STATUS_CANCELLED = "cancelled"


INVOICE_STATUS_CHOICES = [
    (INVOICE_STATUS_DRAFT, "Draft"),
    (INVOICE_STATUS_PENDING_SEND, "Pending Send"),
    (INVOICE_STATUS_SENT, "Sent"),
    (INVOICE_STATUS_VOID, "Void"),

    # Legacy choices kept so old records do not break admin/forms if they exist.
    (INVOICE_STATUS_PENDING, "Pending"),
    (INVOICE_STATUS_PARTIALLY_PAID, "Partially Paid"),
    (INVOICE_STATUS_PAID, "Paid"),
    (INVOICE_STATUS_OVERDUE, "Overdue"),
    (INVOICE_STATUS_CANCELLED, "Cancelled"),
]


INVOICE_PAYMENT_STATUS_UNPAID = "unpaid"
INVOICE_PAYMENT_STATUS_PARTIAL = "partial"
INVOICE_PAYMENT_STATUS_PAID = "paid"
INVOICE_PAYMENT_STATUS_OVERPAID = "overpaid"
INVOICE_PAYMENT_STATUS_VOID = "void"


INVOICE_PAYMENT_STATUS_CHOICES = [
    (INVOICE_PAYMENT_STATUS_UNPAID, "Unpaid"),
    (INVOICE_PAYMENT_STATUS_PARTIAL, "Partial"),
    (INVOICE_PAYMENT_STATUS_PAID, "Paid"),
    (INVOICE_PAYMENT_STATUS_OVERPAID, "Overpaid"),
    (INVOICE_PAYMENT_STATUS_VOID, "Void"),
]


INVOICE_EDITABLE_STATUSES = [
    INVOICE_STATUS_DRAFT,
]

INVOICE_GENERATE_ALLOWED_STATUSES = [
    INVOICE_STATUS_DRAFT,
]

INVOICE_SEND_ALLOWED_STATUSES = [
    INVOICE_STATUS_PENDING_SEND,
    INVOICE_STATUS_SENT,
]

INVOICE_VOID_ALLOWED_STATUSES = [
    INVOICE_STATUS_PENDING_SEND,
    INVOICE_STATUS_SENT,
]

INVOICE_PDF_ALLOWED_STATUSES = [
    INVOICE_STATUS_PENDING_SEND,
    INVOICE_STATUS_SENT,
    INVOICE_STATUS_VOID,

    # Legacy compatibility.
    INVOICE_STATUS_PENDING,
    INVOICE_STATUS_PARTIALLY_PAID,
    INVOICE_STATUS_PAID,
    INVOICE_STATUS_OVERDUE,
    INVOICE_STATUS_CANCELLED,
]

INVOICE_LOCKED_STATUSES = [
    INVOICE_STATUS_PENDING_SEND,
    INVOICE_STATUS_SENT,
    INVOICE_STATUS_VOID,
]

INVOICE_ACTIVE_STATUSES = [
    INVOICE_STATUS_DRAFT,
    INVOICE_STATUS_PENDING_SEND,
    INVOICE_STATUS_SENT,
]

INVOICE_PAYABLE_STATUSES = [
    INVOICE_STATUS_PENDING_SEND,
    INVOICE_STATUS_SENT,

    # Legacy compatibility while payments module is still being adjusted.
    INVOICE_STATUS_PENDING,
]

INVOICE_OPEN_PAYMENT_STATUSES = [
    INVOICE_PAYMENT_STATUS_UNPAID,
    INVOICE_PAYMENT_STATUS_PARTIAL,
    INVOICE_PAYMENT_STATUS_OVERPAID,
]