# Generated by Django 5.2.14 on 2026-05-26 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_slug_company_company_slug_idx'),
        ('platform_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSubscription',
            fields=[
                ('id_subscription', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=30)),
                ('start_date', models.DateField()),
                ('renewal_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='platform_subscriptions', to='companies.company')),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='platform_plans.platformplan')),
            ],
            options={
                'db_table': 'platform_subscription',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='platform_sub_status_idx'), models.Index(fields=['renewal_date'], name='platform_sub_renew_idx')],
            },
        ),
    ]
