OPPORTUNITY_STATUS_NEW = "new"
OPPORTUNITY_STATUS_QUALIFIED = "qualified"
OPPORTUNITY_STATUS_WON = "won"
OPPORTUNITY_STATUS_CANCELLED = "cancelled"
OPPORTUNITY_STATUS_CONVERTED = "converted"

OPPORTUNITY_STATUS_CHOICES = [
    (OPPORTUNITY_STATUS_NEW, "New"),
    (OPPORTUNITY_STATUS_QUALIFIED, "Qualified"),
    (OPPORTUNITY_STATUS_WON, "Won"),
    (OPPORTUNITY_STATUS_CANCELLED, "Cancelled"),
    (OPPORTUNITY_STATUS_CONVERTED, "Converted"),
]

OPPORTUNITY_STATUS_FORM_CHOICES = [
    (OPPORTUNITY_STATUS_NEW, "New"),
    (OPPORTUNITY_STATUS_QUALIFIED, "Qualified"),
    (OPPORTUNITY_STATUS_WON, "Won"),
    (OPPORTUNITY_STATUS_CANCELLED, "Cancelled"),
]


LEAD_STATUS_NEW = OPPORTUNITY_STATUS_NEW
LEAD_STATUS_QUALIFIED = OPPORTUNITY_STATUS_QUALIFIED
LEAD_STATUS_WON = OPPORTUNITY_STATUS_WON
LEAD_STATUS_CANCELLED = OPPORTUNITY_STATUS_CANCELLED
LEAD_STATUS_CONVERTED = OPPORTUNITY_STATUS_CONVERTED

LEAD_STATUS_CHOICES = OPPORTUNITY_STATUS_CHOICES


LEAD_SOURCE_WEBSITE = "website"
LEAD_SOURCE_PHONE = "phone"
LEAD_SOURCE_EMAIL = "email"
LEAD_SOURCE_REFERRAL = "referral"
LEAD_SOURCE_SOCIAL = "social"
LEAD_SOURCE_LOCAL_SERVICES_ADS = "local_services_ads"
LEAD_SOURCE_OTHER = "other"

LEAD_SOURCE_CHOICES = [
    (LEAD_SOURCE_WEBSITE, "Website"),
    (LEAD_SOURCE_PHONE, "Phone"),
    (LEAD_SOURCE_EMAIL, "Email"),
    (LEAD_SOURCE_REFERRAL, "Referral"),
    (LEAD_SOURCE_SOCIAL, "Social Media"),
    (LEAD_SOURCE_LOCAL_SERVICES_ADS, "Local Services Ads"),
    (LEAD_SOURCE_OTHER, "Other"),
]