CRM_SIDEBAR_ITEMS = [
    {
        "label": "Dashboard",
        "url": "/",
        "active_path": "/",
        "module": None,
        "global_only": False,
    },
    {
        "label": "Companies",
        "url": "/companies/",
        "active_path": "/companies/",
        "module": "companies",
        "global_only": True,
    },
    {
        "label": "Company Modules",
        "url": "/company-modules/",
        "active_path": "/company-modules/",
        "module": "company_modules",
        "global_only": True,
    },
    {
        "label": "Employees & Users",
        "url": "/accounts/users/",
        "active_path": "/accounts/users/",
        "module": "users",
        "global_only": False,
    },
    {
        "label": "Roles",
        "url": "/accounts/roles/",
        "active_path": "/accounts/roles/",
        "module": "roles",
        "global_only": False,
    },
    {
        "label": "Notifications",
        "url": "/notifications/",
        "active_path": "/notifications/",
        "module": "notifications",
        "global_only": False,
    },
    {
        "label": "Clients",
        "url": "/clients/",
        "active_path": "/clients/",
        "module": "clients",
        "global_only": False,
    },
    {
        "label": "Opportunities",
        "url": "/opportunities/",
        "active_path": "/opportunities/",
        "module": "opportunities",
        "global_only": False,
    },
    {
        "label": "Projects",
        "url": "/projects/",
        "active_path": "/projects/",
        "module": "projects",
        "global_only": False,
    },
    {
        "label": "Inspections",
        "url": "/inspections/",
        "active_path": "/inspections/",
        "module": "inspections",
        "global_only": False,
    },
    {
        "label": "Calendar",
        "url": "/calendar-events/",
        "active_path": "/calendar-events/",
        "module": "calendar_events",
        "global_only": False,
    },
    {
        "label": "Estimates",
        "url": "/estimates/",
        "active_path": "/estimates/",
        "module": "estimates",
        "global_only": False,
    },
    {
        "label": "Invoices",
        "url": "/invoices/",
        "active_path": "/invoices/",
        "module": "invoices",
        "global_only": False,
    },
    {
        "label": "Payments",
        "url": "/payments/",
        "active_path": "/payments/",
        "module": "payments",
        "global_only": False,
    },
    {
        "label": "Contracts",
        "url": "/contracts/",
        "active_path": "/contracts/",
        "module": "contracts",
        "global_only": False,
    },
    {
        "label": "Reports",
        "url": "/reports/reports/financial-summary.csv",
        "active_path": "/reports/",
        "module": "reports",
        "global_only": False,
    },
    {
        "label": "History",
        "url": "/system-logs/",
        "active_path": "/system-logs/",
        "module": "system_logs",
        "global_only": False,
    },
    {
        "label": "Django Admin",
        "url": "/admin/",
        "active_path": "/admin/",
        "module": None,
        "global_only": True,
    },
]