from decimal import Decimal

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DetailView, ListView, TemplateView, UpdateView
from rest_framework.decorators import action
from rest_framework.exceptions import PermissionDenied
from rest_framework.response import Response

from apps.core.mixins import TenantModelViewSet
from apps.core.template_permissions import (
    ModulePermissionRequiredMixin,
    PERMISSION_APPROVE,
    PERMISSION_CREATE,
    PERMISSION_DELETE,
    PERMISSION_EDIT,
    PERMISSION_VIEW,
    require_module_action_or_403,
    user_can_module_action,
)
from apps.invoices.models import Invoice
from apps.invoices.models.choices import INVOICE_PAYABLE_STATUSES

from .forms import PaymentForm
from .models import ClientCreditMovement, Payment
from .permissions import user_can_access_payment
from .selectors import (
    get_all_clients_financial_summaries,
    get_all_financial_clients,
    get_client_financial_statement,
    get_financial_movements_queryset,
    payment_list_for_user,
)
from .serializers import PaymentSerializer
from .services import (
    apply_client_credit_to_invoice,
    get_credit_account_balance,
    payment_cancel,
    payment_confirm,
    payment_mark_paid,
    payment_mark_pending,
    payment_reject,
    payment_update,
    payment_verify,
    payment_void,
    recalculate_invoice_payment_status,
    register_payment,
)


def invoice_queryset_for_user(user):
    queryset = Invoice.objects.select_related(
        "id_company",
        "id_client",
        "id_project",
    ).filter(
        status__in=INVOICE_PAYABLE_STATUSES,
    )

    if not user or not user.is_authenticated:
        return queryset.none()

    if user.is_superuser:
        return queryset

    return queryset.filter(id_company=user.id_company_id)


def refresh_payment_related_invoices(payment):
    if not payment or not payment.pk:
        return

    payment.refresh_from_db()

    for allocation in payment.allocations.select_related("id_invoice").all():
        recalculate_invoice_payment_status(allocation.id_invoice)

    for movement in ClientCreditMovement.objects.select_related("id_invoice").filter(
        id_payment=payment,
        movement_type="applied",
        id_invoice__isnull=False,
    ):
        recalculate_invoice_payment_status(movement.id_invoice)

    if payment.id_invoice:
        recalculate_invoice_payment_status(payment.id_invoice)


def enrich_payment_for_ui(payment):
    """Attach UI-only amounts used by compact templates.

    amount = money received in this operation + client credit consumed.
    credit = new credit generated by overpayment.
    allocations include cash allocations plus credit applications.
    """
    if not payment or not payment.pk:
        return payment

    cash_allocated = Decimal("0.00")
    for allocation in payment.allocations.all():
        cash_allocated += allocation.amount or Decimal("0.00")

    credit_applied = Decimal("0.00")
    credit_created = Decimal("0.00")
    credit_voided = Decimal("0.00")

    for movement in ClientCreditMovement.objects.filter(id_payment=payment):
        amount = movement.amount or Decimal("0.00")
        if movement.movement_type == "applied":
            credit_applied += amount
        elif movement.movement_type == "created":
            credit_created += amount
        elif movement.movement_type == "voided":
            credit_voided += amount

    operation_amount = (payment.amount or Decimal("0.00")) + credit_applied
    credit_amount = credit_created - credit_voided

    if credit_amount < Decimal("0.00"):
        credit_amount = Decimal("0.00")

    payment.ui_cash_allocated_amount = cash_allocated
    payment.ui_credit_applied_amount = credit_applied
    payment.ui_allocated_amount = cash_allocated + credit_applied
    payment.ui_operation_amount = operation_amount
    payment.ui_credit_amount = credit_amount
    payment.ui_credit_only = bool((payment.amount or Decimal("0.00")) <= Decimal("0.00") and credit_applied > Decimal("0.00"))
    payment.ui_credit_applications = ClientCreditMovement.objects.select_related(
        "id_invoice",
        "id_invoice__id_project",
    ).filter(
        id_payment=payment,
        movement_type="applied",
        id_invoice__isnull=False,
    )

    return payment


def build_payment_balance_summary(payments):
    total_amount = Decimal("0.00")
    total_allocated = Decimal("0.00")
    total_available_credit = Decimal("0.00")
    confirmed_total = Decimal("0.00")
    pending_total = Decimal("0.00")
    voided_total = Decimal("0.00")

    for payment in payments:
        enrich_payment_for_ui(payment)

        amount = getattr(payment, "ui_operation_amount", None)
        if amount is None:
            amount = payment.amount or Decimal("0.00")

        allocated = getattr(payment, "ui_allocated_amount", None)
        if allocated is None:
            allocated = payment.allocated_amount or Decimal("0.00")

        available = getattr(payment, "ui_credit_amount", None)
        if available is None:
            available = payment.available_amount or Decimal("0.00")

        total_amount += amount
        total_allocated += allocated
        total_available_credit += available

        if payment.status in ["paid", "verified", "confirmed"]:
            confirmed_total += amount
        elif payment.status == "pending_payment":
            pending_total += amount
        elif payment.status in ["rejected", "cancelled", "void"]:
            voided_total += amount

    return {
        "count": len(payments),
        "total_amount": total_amount,
        "total_allocated": total_allocated,
        "total_available_credit": total_available_credit,
        "confirmed_total": confirmed_total,
        "pending_total": pending_total,
        "voided_total": voided_total,
    }


def build_financial_overview_for_user(user):
    company = get_finance_company_for_user(user)

    overview = {
        "total_invoiced": Decimal("0.00"),
        "total_paid": Decimal("0.00"),
        "total_allocated": Decimal("0.00"),
        "total_balance_due": Decimal("0.00"),
        "total_credit_balance": Decimal("0.00"),
        "total_open_invoices": 0,
    }

    if not company:
        return overview

    for summary in get_all_clients_financial_summaries(company):
        overview["total_invoiced"] += summary.get("total_invoiced", Decimal("0.00"))
        overview["total_paid"] += summary.get("total_paid", Decimal("0.00"))
        overview["total_allocated"] += summary.get("total_allocated", Decimal("0.00"))
        overview["total_balance_due"] += summary.get("balance_due", Decimal("0.00"))
        overview["total_credit_balance"] += summary.get("credit_balance", Decimal("0.00"))
        overview["total_open_invoices"] += summary.get("open_invoices", 0)

    return overview


class PaymentListView(LoginRequiredMixin, ModulePermissionRequiredMixin, ListView):
    module_name = "payments"
    permission_required = PERMISSION_VIEW
    template_name = "payments/list.html"
    context_object_name = "payments"
    paginate_by = 20
    login_url = "/login/"

    def get_queryset(self):
        queryset = payment_list_for_user(self.request.user)

        for payment in queryset[:100]:
            refresh_payment_related_invoices(payment)
            enrich_payment_for_ui(payment)

        refreshed_queryset = payment_list_for_user(self.request.user)

        for payment in refreshed_queryset[:100]:
            enrich_payment_for_ui(payment)

        return refreshed_queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["page_title"] = "Payments"
        context["can_create_payments"] = user_can_module_action(
            self.request.user,
            "payments",
            PERMISSION_CREATE,
        )
        context["can_edit_payments"] = user_can_module_action(
            self.request.user,
            "payments",
            PERMISSION_EDIT,
        )
        context["can_delete_payments"] = user_can_module_action(
            self.request.user,
            "payments",
            PERMISSION_DELETE,
        )
        context["can_approve_payments"] = user_can_module_action(
            self.request.user,
            "payments",
            PERMISSION_APPROVE,
        )

        for payment in context.get("payments", []):
            enrich_payment_for_ui(payment)

        all_payments = list(payment_list_for_user(self.request.user))
        for payment in all_payments:
            enrich_payment_for_ui(payment)

        context["payment_balance_summary"] = build_payment_balance_summary(all_payments)
        context["financial_overview"] = build_financial_overview_for_user(self.request.user)

        return context


class PaymentDetailView(LoginRequiredMixin, ModulePermissionRequiredMixin, DetailView):
    module_name = "payments"
    permission_required = PERMISSION_VIEW
    model = Payment
    template_name = "payments/detail.html"
    context_object_name = "payment"
    pk_url_kwarg = "id_payment"
    login_url = "/login/"

    def get_queryset(self):
        return payment_list_for_user(self.request.user)

    def get_object(self, queryset=None):
        payment = super().get_object(queryset)
        refresh_payment_related_invoices(payment)
        payment.refresh_from_db()
        return payment

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["page_title"] = "Payment Details"
        context["can_edit_payments"] = user_can_module_action(
            self.request.user,
            "payments",
            PERMISSION_EDIT,
        )
        context["can_delete_payments"] = user_can_module_action(
            self.request.user,
            "payments",
            PERMISSION_DELETE,
        )
        context["can_approve_payments"] = user_can_module_action(
            self.request.user,
            "payments",
            PERMISSION_APPROVE,
        )

        company = self.object.id_company
        client = self.object.id_client

        context["allocations"] = self.object.allocations.select_related(
            "id_invoice",
            "id_project",
        ).all()

        context["credit_applications"] = ClientCreditMovement.objects.select_related(
            "id_invoice",
            "id_invoice__id_project",
        ).filter(
            id_payment=self.object,
            movement_type="applied",
        )

        enrich_payment_for_ui(self.object)

        context["credit_movements"] = ClientCreditMovement.objects.select_related(
            "id_payment",
            "id_invoice",
        ).filter(
            id_payment=self.object,
        )

        if company and client:
            context["credit_balance"] = get_credit_account_balance(
                company=company,
                client=client,
            )
            context["movements"] = get_financial_movements_queryset(company).filter(
                id_payment=self.object,
            )
        else:
            context["credit_balance"] = 0
            context["movements"] = []

        return context


class PaymentCreateView(LoginRequiredMixin, ModulePermissionRequiredMixin, CreateView):
    module_name = "payments"
    permission_required = PERMISSION_CREATE
    model = Payment
    form_class = PaymentForm
    template_name = "payments/form.html"
    success_url = reverse_lazy("payments:payment_list")
    login_url = "/login/"

    def dispatch(self, request, *args, **kwargs):
        self.invoice = None

        id_invoice = (
            self.kwargs.get("id_invoice")
            or self.request.GET.get("invoice_id")
            or self.request.GET.get("id_invoice")
        )

        if id_invoice:
            self.invoice = get_object_or_404(
                invoice_queryset_for_user(request.user),
                id_invoice=id_invoice,
            )

            recalculate_invoice_payment_status(self.invoice)
            self.invoice.refresh_from_db()

            if self.invoice.balance_due <= 0:
                messages.error(
                    request,
                    "This invoice does not have pending balance.",
                )
                return redirect(
                    "invoices:invoice_detail",
                    id_invoice=self.invoice.id_invoice,
                )

        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super().get_initial()

        if self.invoice:
            initial.update(
                {
                    "id_client": self.invoice.id_client,
                    "id_project": self.invoice.id_project,
                    "id_invoice": self.invoice,
                    "amount": self.invoice.balance_due,
                }
            )

        return initial

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        kwargs["invoice"] = self.invoice

        return kwargs

    def get_success_url(self):
        return reverse_lazy("payments:payment_list")

    def form_valid(self, form):
        self.object = form.save(commit=False)

        try:
            with transaction.atomic():
                register_payment(
                    payment=self.object,
                    user=self.request.user,
                    allow_overpayment=True,
                    allocations_data=form.get_allocations_data(),
                )

                client_credit_used = Decimal("0.00")

                for credit_application in form.get_credit_applications_data():
                    invoice = credit_application["invoice"]
                    invoice.refresh_from_db()

                    credit_amount_to_apply = credit_application["amount"]

                    if credit_amount_to_apply > invoice.balance_due:
                        credit_amount_to_apply = invoice.balance_due

                    if credit_amount_to_apply <= Decimal("0.00"):
                        continue

                    apply_client_credit_to_invoice(
                        company=self.object.id_company,
                        client=self.object.id_client,
                        invoice=invoice,
                        amount=credit_amount_to_apply,
                        user=self.request.user,
                        payment=self.object,
                    )

                    client_credit_used += credit_amount_to_apply

                refresh_payment_related_invoices(self.object)

            credit_amount = form.get_credit_amount()

            success_message = f"Payment {self.object.payment_number} registered successfully."

            if client_credit_used > 0:
                success_message += f" ${client_credit_used} was consumed from the client credit balance."

            if credit_amount > 0:
                success_message += f" ${credit_amount} was added as client credit balance."

            messages.success(self.request, success_message)

            return redirect(self.get_success_url())

        except Exception as error:
            messages.error(
                self.request,
                f"Payment could not be registered: {error}",
            )

            return self.form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Please review the payment form.")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        form = context.get("form")

        context["page_title"] = "Create Payment"
        context["form_title"] = "Create Payment"
        context["submit_label"] = "Register Payment"
        context["invoice"] = self.invoice
        context["allocation_fields"] = getattr(form, "allocation_fields", [])

        return context


class PaymentUpdateView(LoginRequiredMixin, ModulePermissionRequiredMixin, UpdateView):
    module_name = "payments"
    permission_required = PERMISSION_EDIT
    model = Payment
    form_class = PaymentForm
    template_name = "payments/form.html"
    context_object_name = "payment"
    pk_url_kwarg = "id_payment"
    login_url = "/login/"

    def get_queryset(self):
        return payment_list_for_user(self.request.user).filter(
            status__in=[
                "pending_payment",
                "paid",
            ]
        )

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user

        return kwargs

    def get_success_url(self):
        return reverse_lazy(
            "payments:payment_detail",
            kwargs={"id_payment": self.object.id_payment},
        )

    def form_valid(self, form):
        self.object = form.save(commit=False)

        try:
            payment_update(
                self.object,
                id_client=self.object.id_client,
                id_project=self.object.id_project,
                id_invoice=self.object.id_invoice,
                amount=self.object.amount,
                payment_method=self.object.payment_method,
                receipt_file=self.object.receipt_file,
                notes=self.object.notes,
                reference_code=self.object.reference_code,
                voucher_code=self.object.voucher_code,
                payment_date=self.object.payment_date,
            )

            register_payment(
                payment=self.object,
                user=self.request.user,
                allow_overpayment=True,
                allocations_data=form.get_allocations_data(),
            )

            refresh_payment_related_invoices(self.object)

            messages.success(self.request, "Payment updated successfully.")

            return redirect(self.get_success_url())

        except Exception as error:
            messages.error(
                self.request,
                f"Payment could not be updated: {error}",
            )

            return self.form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Please review the payment form.")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        form = context.get("form")

        context["page_title"] = "Edit Payment"
        context["form_title"] = "Edit Payment"
        context["submit_label"] = "Update Payment"
        context["invoice"] = self.object.id_invoice
        context["allocation_fields"] = getattr(form, "allocation_fields", [])

        return context


@require_POST
def payment_mark_pending_view(request, id_payment, company_slug=None):
    permission_response = require_module_action_or_403(
        request.user,
        "payments",
        PERMISSION_EDIT,
    )

    if permission_response:
        return permission_response

    payment = get_object_or_404(payment_list_for_user(request.user), id_payment=id_payment)

    if not user_can_access_payment(request.user, payment):
        return HttpResponseForbidden("Permission denied.")

    try:
        payment_mark_pending(payment)
        refresh_payment_related_invoices(payment)
        messages.success(request, "Payment marked as pending successfully.")
    except Exception as error:
        messages.error(request, f"Payment could not be marked as pending: {error}")

    return redirect("payments:payment_detail", id_payment=payment.id_payment)


@require_POST
def payment_mark_paid_view(request, id_payment, company_slug=None):
    permission_response = require_module_action_or_403(
        request.user,
        "payments",
        PERMISSION_EDIT,
    )

    if permission_response:
        return permission_response

    payment = get_object_or_404(payment_list_for_user(request.user), id_payment=id_payment)

    if not user_can_access_payment(request.user, payment):
        return HttpResponseForbidden("Permission denied.")

    try:
        payment_mark_paid(payment)
        refresh_payment_related_invoices(payment)
        messages.success(request, "Payment marked as paid successfully.")
    except Exception as error:
        messages.error(request, f"Payment could not be marked as paid: {error}")

    return redirect("payments:payment_detail", id_payment=payment.id_payment)


@require_POST
def payment_verify_view(request, id_payment, company_slug=None):
    permission_response = require_module_action_or_403(
        request.user,
        "payments",
        PERMISSION_APPROVE,
    )

    if permission_response:
        return permission_response

    payment = get_object_or_404(payment_list_for_user(request.user), id_payment=id_payment)

    if not user_can_access_payment(request.user, payment):
        return HttpResponseForbidden("Permission denied.")

    try:
        payment_verify(payment, request.user)
        refresh_payment_related_invoices(payment)
        messages.success(request, "Payment verified successfully.")
    except Exception as error:
        messages.error(request, f"Payment could not be verified: {error}")

    return redirect("payments:payment_detail", id_payment=payment.id_payment)


@require_POST
def payment_confirm_view(request, id_payment, company_slug=None):
    permission_response = require_module_action_or_403(
        request.user,
        "payments",
        PERMISSION_APPROVE,
    )

    if permission_response:
        return permission_response

    payment = get_object_or_404(payment_list_for_user(request.user), id_payment=id_payment)

    if not user_can_access_payment(request.user, payment):
        return HttpResponseForbidden("Permission denied.")

    try:
        payment_confirm(payment, user=request.user)
        refresh_payment_related_invoices(payment)
        messages.success(request, "Payment confirmed successfully.")
    except Exception as error:
        messages.error(request, f"Payment could not be confirmed: {error}")

    return redirect("payments:payment_detail", id_payment=payment.id_payment)


@require_POST
def payment_reject_view(request, id_payment, company_slug=None):
    permission_response = require_module_action_or_403(
        request.user,
        "payments",
        PERMISSION_APPROVE,
    )

    if permission_response:
        return permission_response

    payment = get_object_or_404(payment_list_for_user(request.user), id_payment=id_payment)

    if not user_can_access_payment(request.user, payment):
        return HttpResponseForbidden("Permission denied.")

    try:
        payment_reject(payment)
        refresh_payment_related_invoices(payment)
        messages.success(request, "Payment rejected successfully.")
    except Exception as error:
        messages.error(request, f"Payment could not be rejected: {error}")

    return redirect("payments:payment_detail", id_payment=payment.id_payment)


@require_POST
def payment_cancel_view(request, id_payment, company_slug=None):
    permission_response = require_module_action_or_403(
        request.user,
        "payments",
        PERMISSION_APPROVE,
    )

    if permission_response:
        return permission_response

    payment = get_object_or_404(payment_list_for_user(request.user), id_payment=id_payment)

    if not user_can_access_payment(request.user, payment):
        return HttpResponseForbidden("Permission denied.")

    try:
        payment_cancel(payment)
        refresh_payment_related_invoices(payment)
        messages.success(request, "Payment cancelled successfully.")
    except Exception as error:
        messages.error(request, f"Payment could not be cancelled: {error}")

    return redirect("payments:payment_detail", id_payment=payment.id_payment)


def payment_void_view(request, id_payment, company_slug=None):
    permission_response = require_module_action_or_403(
        request.user,
        "payments",
        PERMISSION_APPROVE,
    )

    if permission_response:
        return permission_response

    payment = get_object_or_404(payment_list_for_user(request.user), id_payment=id_payment)

    if not user_can_access_payment(request.user, payment):
        return HttpResponseForbidden("Permission denied.")

    if request.method == "GET":
        messages.error(request, "Please use the Void button and enter the void reason.")
        return redirect("payments:payment_detail", id_payment=payment.id_payment)

    if request.method != "POST":
        return HttpResponseForbidden("Invalid request method.")

    reason = request.POST.get("void_reason", "").strip()

    try:
        payment_void(
            payment=payment,
            user=request.user,
            reason=reason,
        )

        refresh_payment_related_invoices(payment)
        payment.refresh_from_db()

        messages.success(request, "Payment voided successfully.")

        return redirect("payments:payment_list")

    except Exception as error:
        messages.error(request, f"Payment could not be voided: {error}")
        return redirect("payments:payment_detail", id_payment=payment.id_payment)


@require_POST
def apply_credit_to_invoice_view(request, id_invoice, company_slug=None):
    permission_response = require_module_action_or_403(
        request.user,
        "payments",
        PERMISSION_CREATE,
    )

    if permission_response:
        return permission_response

    invoice = get_object_or_404(
        invoice_queryset_for_user(request.user),
        id_invoice=id_invoice,
    )

    recalculate_invoice_payment_status(invoice)
    invoice.refresh_from_db()

    amount = request.POST.get("credit_amount", "").strip()

    try:
        apply_client_credit_to_invoice(
            company=invoice.id_company,
            client=invoice.id_client,
            invoice=invoice,
            amount=amount,
            user=request.user,
        )

        recalculate_invoice_payment_status(invoice)

        messages.success(
            request,
            f"Credit balance applied successfully to invoice {invoice.invoice_number or invoice.id_invoice}.",
        )

    except Exception as error:
        messages.error(
            request,
            f"Credit balance could not be applied: {error}",
        )

    return redirect(
        "invoices:invoice_detail",
        id_invoice=invoice.id_invoice,
    )


class PaymentViewSet(TenantModelViewSet):
    module_name = "payments"
    queryset = Payment.objects.select_related(
        "id_company",
        "id_client",
        "id_invoice",
        "id_invoice__id_company",
        "id_invoice__id_client",
        "id_project",
        "verified_by",
        "voided_by",
        "created_by",
    ).prefetch_related(
        "allocations",
    ).all()
    serializer_class = PaymentSerializer
    tenant_filter_path = "id_company"
    tenant_create_field = None

    def get_queryset(self):
        return payment_list_for_user(self.request.user)

    def perform_create(self, serializer):
        payment = serializer.save()

        if (
            not self.request.user.is_superuser
            and payment.id_company_id
            and payment.id_company_id != self.request.user.id_company_id
        ):
            raise PermissionDenied("You can only create payments for your company.")

        try:
            register_payment(
                payment=payment,
                user=self.request.user,
                allow_overpayment=True,
            )
            refresh_payment_related_invoices(payment)
        except Exception as error:
            raise PermissionDenied(str(error))

    def perform_update(self, serializer):
        payment = self.get_object()

        if not user_can_access_payment(self.request.user, payment):
            raise PermissionDenied("You can only update payments from your company.")

        instance = serializer.save()
        refresh_payment_related_invoices(instance)

    @action(detail=True, methods=["post"])
    def mark_paid(self, request, pk=None):
        if not user_can_module_action(request.user, "payments", PERMISSION_EDIT):
            raise PermissionDenied("You do not have permission to edit payments.")

        payment = self.get_object()
        payment_mark_paid(payment)
        refresh_payment_related_invoices(payment)

        return Response(
            {
                "detail": "Payment marked as paid successfully.",
                "payment_id": payment.id_payment,
                "payment_number": payment.payment_number,
                "voucher_code": payment.voucher_code,
                "status": payment.status,
            }
        )

    @action(detail=True, methods=["post"])
    def verify(self, request, pk=None):
        if not user_can_module_action(request.user, "payments", PERMISSION_APPROVE):
            raise PermissionDenied("You do not have permission to verify payments.")

        payment = self.get_object()
        payment_verify(payment, request.user)
        refresh_payment_related_invoices(payment)

        return Response(
            {
                "detail": "Payment verified successfully.",
                "payment_id": payment.id_payment,
                "payment_number": payment.payment_number,
                "voucher_code": payment.voucher_code,
                "status": payment.status,
            }
        )

    @action(detail=True, methods=["post"])
    def confirm(self, request, pk=None):
        if not user_can_module_action(request.user, "payments", PERMISSION_APPROVE):
            raise PermissionDenied("You do not have permission to confirm payments.")

        payment = self.get_object()
        payment_confirm(payment, user=request.user)
        refresh_payment_related_invoices(payment)

        return Response(
            {
                "detail": "Payment confirmed successfully.",
                "payment_id": payment.id_payment,
                "payment_number": payment.payment_number,
                "status": payment.status,
            }
        )

    @action(detail=True, methods=["post"])
    def reject(self, request, pk=None):
        if not user_can_module_action(request.user, "payments", PERMISSION_APPROVE):
            raise PermissionDenied("You do not have permission to reject payments.")

        payment = self.get_object()
        payment_reject(payment)
        refresh_payment_related_invoices(payment)

        return Response(
            {
                "detail": "Payment rejected successfully.",
                "payment_id": payment.id_payment,
                "status": payment.status,
            }
        )

    @action(detail=True, methods=["post"])
    def cancel(self, request, pk=None):
        if not user_can_module_action(request.user, "payments", PERMISSION_APPROVE):
            raise PermissionDenied("You do not have permission to cancel payments.")

        payment = self.get_object()
        payment_cancel(payment)
        refresh_payment_related_invoices(payment)

        return Response(
            {
                "detail": "Payment cancelled successfully.",
                "payment_id": payment.id_payment,
                "status": payment.status,
            }
        )

    @action(detail=True, methods=["post"])
    def void(self, request, pk=None):
        if not user_can_module_action(request.user, "payments", PERMISSION_APPROVE):
            raise PermissionDenied("You do not have permission to void payments.")

        payment = self.get_object()
        reason = request.data.get("void_reason", "")

        payment_void(
            payment=payment,
            user=request.user,
            reason=reason,
        )

        refresh_payment_related_invoices(payment)

        return Response(
            {
                "detail": "Payment voided successfully.",
                "payment_id": payment.id_payment,
                "status": payment.status,
            }
        )


def get_finance_company_for_user(user):
    if not user or not user.is_authenticated:
        return None

    company = getattr(user, "id_company", None)

    if company:
        return company

    if user.is_superuser:
        try:
            from apps.companies.models import Company

            return Company.objects.first()
        except Exception:
            return None

    return None


class FinanceClientListView(LoginRequiredMixin, ModulePermissionRequiredMixin, TemplateView):
    module_name = "payments"
    permission_required = PERMISSION_VIEW
    template_name = "payments/finance_clients.html"
    login_url = "/login/"

    def dispatch(self, request, *args, **kwargs):
        self.company = get_finance_company_for_user(request.user)

        if not self.company:
            messages.error(
                request,
                "Your user does not have a company assigned. Please assign a company before using finance.",
            )
            return redirect("payments:payment_list")

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        summaries = get_all_clients_financial_summaries(self.company)

        total_invoiced = 0
        total_paid = 0
        total_allocated = 0
        total_balance_due = 0
        total_credit_balance = 0
        total_open_invoices = 0

        for summary in summaries:
            total_invoiced += summary["total_invoiced"]
            total_paid += summary["total_paid"]
            total_allocated += summary.get("total_allocated", 0)
            total_balance_due += summary["balance_due"]
            total_credit_balance += summary["credit_balance"]
            total_open_invoices += summary["open_invoices"]

        context["page_title"] = "Financial Summary by Client"
        context["summaries"] = summaries
        context["total_invoiced"] = total_invoiced
        context["total_paid"] = total_paid
        context["total_allocated"] = total_allocated
        context["total_balance_due"] = total_balance_due
        context["total_credit_balance"] = total_credit_balance
        context["total_open_invoices"] = total_open_invoices

        return context


class FinanceClientDetailView(LoginRequiredMixin, ModulePermissionRequiredMixin, TemplateView):
    module_name = "payments"
    permission_required = PERMISSION_VIEW
    template_name = "payments/finance_client_detail.html"
    login_url = "/login/"

    def dispatch(self, request, *args, **kwargs):
        self.company = get_finance_company_for_user(request.user)

        if not self.company:
            messages.error(
                request,
                "Your user does not have a company assigned. Please assign a company before using finance.",
            )
            return redirect("payments:payment_list")

        return super().dispatch(request, *args, **kwargs)

    def get_client(self):
        return get_object_or_404(
            get_all_financial_clients(self.company),
            id_client=self.kwargs["id_client"],
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        client = self.get_client()
        statement = get_client_financial_statement(
            company=self.company,
            client=client,
        )

        context["page_title"] = "Client Financial Statement"
        context["client"] = client
        context["summary"] = statement["summary"]
        context["invoices"] = statement["invoices"]
        context["payments"] = statement["payments"]
        context["allocations"] = statement["allocations"]
        context["credit_movements"] = statement["credit_movements"]
        context["movements"] = statement["movements"]
        context["credit_account"] = statement["credit_account"]

        return context