PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PAID = "paid"
PAYMENT_STATUS_FAILED = "failed"
PAYMENT_STATUS_REFUNDED = "refunded"
PAYMENT_STATUS_VOID = "void"

PAYMENT_STATUS_CHOICES = [
    (PAYMENT_STATUS_PENDING, "Pending"),
    (PAYMENT_STATUS_PAID, "Paid"),
    (PAYMENT_STATUS_FAILED, "Failed"),
    (PAYMENT_STATUS_REFUNDED, "Refunded"),
    (PAYMENT_STATUS_VOID, "Void"),
]

PAYMENT_METHOD_MANUAL = "manual"
PAYMENT_METHOD_BANK_TRANSFER = "bank_transfer"
PAYMENT_METHOD_ZELLE = "zelle"
PAYMENT_METHOD_CARD = "card"
PAYMENT_METHOD_CASH = "cash"
PAYMENT_METHOD_OTHER = "other"

PAYMENT_METHOD_CHOICES = [
    (PAYMENT_METHOD_MANUAL, "Manual"),
    (PAYMENT_METHOD_BANK_TRANSFER, "Bank Transfer"),
    (PAYMENT_METHOD_ZELLE, "Zelle"),
    (PAYMENT_METHOD_CARD, "Card"),
    (PAYMENT_METHOD_CASH, "Cash"),
    (PAYMENT_METHOD_OTHER, "Other"),
]