# Generated by Django 5.2.14 on 2026-05-27 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_slug_company_company_slug_idx'),
        ('platform_subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCalendarEvent',
            fields=[
                ('id_event', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('event_type', models.CharField(choices=[('manual', 'Manual Event'), ('renewal', 'Renewal Reminder'), ('payment_follow_up', 'Payment Follow Up'), ('company_review', 'Company Review'), ('suspension', 'Suspension Review'), ('other', 'Other')], db_index=True, default='manual', max_length=50)),
                ('start_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], db_index=True, default='normal', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('id_company', models.ForeignKey(blank=True, db_column='id_company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_calendar_events', to='companies.company')),
                ('id_subscription', models.ForeignKey(blank=True, db_column='id_subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_calendar_events', to='platform_subscriptions.platformsubscription')),
            ],
            options={
                'db_table': 'platform_calendar_event',
                'ordering': ['start_date', 'start_time', 'title'],
                'indexes': [models.Index(fields=['event_type'], name='platform_cal_type_idx'), models.Index(fields=['status'], name='platform_cal_status_idx'), models.Index(fields=['priority'], name='platform_cal_priority_idx'), models.Index(fields=['start_date'], name='platform_cal_start_idx')],
            },
        ),
    ]
