DOCUMENT_TYPE_PROFORMA = "proforma"
DOCUMENT_TYPE_INVOICE = "invoice"

DOCUMENT_TYPE_CHOICES = [
    (DOCUMENT_TYPE_PROFORMA, "Proforma"),
    (DOCUMENT_TYPE_INVOICE, "Invoice"),
]

DOCUMENT_STATUS_DRAFT = "draft"
DOCUMENT_STATUS_SENT = "sent"
DOCUMENT_STATUS_PAID = "paid"
DOCUMENT_STATUS_VOID = "void"
DOCUMENT_STATUS_OVERDUE = "overdue"

DOCUMENT_STATUS_CHOICES = [
    (DOCUMENT_STATUS_DRAFT, "Draft"),
    (DOCUMENT_STATUS_SENT, "Sent"),
    (DOCUMENT_STATUS_PAID, "Paid"),
    (DOCUMENT_STATUS_VOID, "Void"),
    (DOCUMENT_STATUS_OVERDUE, "Overdue"),
]