# Generated by Django 5.2.14 on 2026-05-19 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id_file', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='projects.project')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_file',
                'ordering': ['-created_at'],
            },
        ),
    ]
