# Generated by Django 5.2.14 on 2026-05-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_slug_company_company_slug_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEmailLog',
            fields=[
                ('id_email_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=180)),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(choices=[('test', 'Test'), ('subscription_expiring', 'Subscription Expiring'), ('subscription_expired', 'Subscription Expired'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('document_created', 'Document Created')], db_index=True, default='test', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('message', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_company', models.ForeignKey(blank=True, db_column='id_company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_email_logs', to='companies.company')),
            ],
            options={
                'db_table': 'platform_email_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='platform_email_status_idx'), models.Index(fields=['email_type'], name='platform_email_type_idx')],
            },
        ),
    ]
