# Generated by Django 5.2.15 on 2026-06-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformplan',
            name='custom_cycle_count',
            field=models.PositiveIntegerField(blank=True, help_text='Used only when billing cycle is Custom.', null=True),
        ),
        migrations.AddField(
            model_name='platformplan',
            name='custom_cycle_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], help_text='Used only when billing cycle is Custom.', max_length=20, null=True),
        ),
    ]
