# Generated by Django 5.2.14 on 2026-05-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0003_alter_company_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id_company__name', 'name']},
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('companies', 'Companies'), ('roles', 'Roles'), ('users', 'Users'), ('employees', 'Employees'), ('notifications', 'Notifications'), ('system_logs', 'System Logs'), ('clients', 'Clients'), ('leads', 'Leads'), ('projects', 'Projects'), ('inspections', 'Inspections'), ('estimates', 'Estimates'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('contracts', 'Contracts'), ('evidence', 'Evidence'), ('supervision', 'Supervision'), ('calendar', 'Calendar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=50),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['status'], name='role_status_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='role_name_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['module'], name='role_perm_module_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['status'], name='user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
    ]
