# Generated by Django 5.2.14 on 2026-05-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_options_alter_role_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('companies', 'Companies'), ('roles', 'Roles'), ('users', 'Users'), ('employees', 'Employees'), ('notifications', 'Notifications'), ('system_logs', 'System Logs'), ('clients', 'Clients'), ('leads', 'Leads'), ('projects', 'Projects'), ('inspections', 'Inspections'), ('estimates', 'Estimates'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('contracts', 'Contracts'), ('evidence', 'Evidence'), ('supervision', 'Supervision'), ('calendar', 'Calendar'), ('notifications', 'Notifications'), ('clients', 'Clients'), ('leads', 'Leads'), ('projects', 'Projects'), ('inspections', 'Inspections'), ('evidence', 'Evidence'), ('supervision', 'Supervision'), ('calendar_events', 'Calendar Events'), ('estimates', 'Estimates'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('contracts', 'Contracts'), ('reports', 'Reports'), ('system_logs', 'System Logs')], max_length=100),
        ),
    ]
