# Generated by Django 5.2.14 on 2026-05-20 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('internal', 'Internal'), ('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], db_index=True, default='starter', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_limit',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['plan'], name='company_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='company_name_idx'),
        ),
    ]
