# Generated by Django 5.2.14 on 2026-05-20 15:34

import apps.companies.models.entities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_name_alter_company_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.companies.models.entities.company_logo_upload_path),
        ),
    ]
