# Generated by Django 5.2.14 on 2026-05-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_company_slug_unique_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
    ]
