# Generated by Django 5.2.15 on 2026-06-10 21:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_remove_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpSetting',
            fields=[
                ('id_smtp_setting', models.BigAutoField(primary_key=True, serialize=False)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('smtp_username', models.EmailField(blank=True, default='', max_length=255)),
                ('smtp_password', models.TextField(blank=True, default='')),
                ('default_from_email', models.EmailField(blank=True, default='', max_length=255)),
                ('from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_test_status', models.CharField(blank=True, max_length=30, null=True)),
                ('last_test_message', models.TextField(blank=True, null=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_company', models.OneToOneField(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='smtp_setting', to='companies.company')),
            ],
            options={
                'verbose_name': 'SMTP Setting',
                'verbose_name_plural': 'SMTP Settings',
                'db_table': 'smtp_setting',
            },
        ),
    ]
