# Generated by Django 5.2.14 on 2026-05-19 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id_lead', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='new', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_assigned_user', models.ForeignKey(blank=True, db_column='id_assigned_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='companies.company')),
                ('id_converted_client', models.ForeignKey(blank=True, db_column='id_converted_client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='clients.client')),
            ],
            options={
                'db_table': 'lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
