# Generated manually for CRM CEO MARKETING integrations module.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleIntegrationConnection",
            fields=[
                ("id_connection", models.BigAutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("google", "Google")], default="google", max_length=40)),
                ("connected_email", models.EmailField(blank=True, max_length=180, null=True)),
                ("display_name", models.CharField(blank=True, max_length=160, null=True)),
                ("status", models.CharField(choices=[("connected", "Connected"), ("disconnected", "Disconnected"), ("expired", "Expired"), ("error", "Error"), ("revoked", "Revoked")], db_index=True, default="disconnected", max_length=40)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("token_payload", models.TextField(blank=True, null=True)),
                ("refresh_token_payload", models.TextField(blank=True, null=True)),
                ("access_token_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("calendar_id", models.CharField(blank=True, default="primary", max_length=255)),
                ("drive_folder_id", models.CharField(blank=True, max_length=255, null=True)),
                ("default_spreadsheet_id", models.CharField(blank=True, max_length=255, null=True)),
                ("analytics_property_id", models.CharField(blank=True, max_length=80, null=True)),
                ("ads_customer_id", models.CharField(blank=True, max_length=40, null=True)),
                ("ads_login_customer_id", models.CharField(blank=True, max_length=40, null=True)),
                ("developer_token", models.CharField(blank=True, max_length=255, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_google_connections", to=settings.AUTH_USER_MODEL)),
                ("id_company", models.ForeignKey(db_column="id_company", on_delete=django.db.models.deletion.CASCADE, related_name="google_integration_connections", to="companies.company")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_google_connections", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "integration_google_connection",
                "ordering": ["-updated_at"],
                "indexes": [models.Index(fields=["id_company", "status"], name="int_conn_company_stat_idx"), models.Index(fields=["provider"], name="int_conn_provider_idx")],
                "constraints": [models.UniqueConstraint(fields=("id_company", "provider"), name="uniq_google_conn_company")],
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                ("id_log", models.BigAutoField(primary_key=True, serialize=False)),
                ("tool", models.CharField(choices=[("calendar", "Calendar / Meet"), ("drive", "Google Drive"), ("sheets", "Google Sheets"), ("analytics", "Google Analytics"), ("ads", "Google Ads"), ("oauth", "Google Connection")], db_index=True, default="oauth", max_length=40)),
                ("action", models.CharField(max_length=160)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("success", "Success"), ("error", "Error"), ("skipped", "Skipped")], db_index=True, max_length=30)),
                ("message", models.TextField(blank=True, null=True)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("connection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="logs", to="integrations.googleintegrationconnection")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("id_company", models.ForeignKey(db_column="id_company", on_delete=django.db.models.deletion.CASCADE, related_name="integration_logs", to="companies.company")),
            ],
            options={"db_table": "integration_log", "ordering": ["-started_at"], "indexes": [models.Index(fields=["id_company", "tool"], name="int_log_company_tool_idx"), models.Index(fields=["status"], name="int_log_status_idx"), models.Index(fields=["started_at"], name="int_log_started_idx")]},
        ),
        migrations.CreateModel(
            name="GoogleCalendarEventLink",
            fields=[
                ("id_calendar_event", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("attendees", models.TextField(blank=True, help_text="Comma separated emails", null=True)),
                ("external_event_id", models.CharField(blank=True, max_length=255, null=True)),
                ("meet_url", models.URLField(blank=True, max_length=700, null=True)),
                ("calendar_html_link", models.URLField(blank=True, max_length=700, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("synced", "Synced"), ("cancelled", "Cancelled"), ("error", "Error")], db_index=True, default="draft", max_length=30)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_events", to="integrations.googleintegrationconnection")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("id_company", models.ForeignKey(db_column="id_company", on_delete=django.db.models.deletion.CASCADE, to="companies.company")),
            ],
            options={"db_table": "integration_calendar_event", "ordering": ["-start_at"], "indexes": [models.Index(fields=["id_company", "start_at"], name="int_cal_company_start_idx"), models.Index(fields=["status"], name="int_cal_status_idx")]},
        ),
        migrations.CreateModel(
            name="GoogleDriveUpload",
            fields=[
                ("id_upload", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=220)),
                ("file", models.FileField(max_length=600, upload_to="integrations/drive_uploads/")),
                ("source_module", models.CharField(blank=True, max_length=80, null=True)),
                ("external_file_id", models.CharField(blank=True, max_length=255, null=True)),
                ("drive_url", models.URLField(blank=True, max_length=700, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("completed", "Completed"), ("error", "Error")], db_index=True, default="pending", max_length=30)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="drive_uploads", to="integrations.googleintegrationconnection")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("id_company", models.ForeignKey(db_column="id_company", on_delete=django.db.models.deletion.CASCADE, to="companies.company")),
            ],
            options={"db_table": "integration_drive_upload", "ordering": ["-created_at"], "indexes": [models.Index(fields=["id_company", "status"], name="int_drive_company_stat_idx")]},
        ),
        migrations.CreateModel(
            name="GoogleSheetExport",
            fields=[
                ("id_export", models.BigAutoField(primary_key=True, serialize=False)),
                ("export_source", models.CharField(choices=[("clients", "Clients"), ("leads", "Leads"), ("invoices", "Invoices"), ("payments", "Payments"), ("suppliers", "Suppliers"), ("supplier_purchases", "Supplier Purchases"), ("analytics", "Analytics Snapshot"), ("ads", "Google Ads Snapshot")], max_length=60)),
                ("spreadsheet_id", models.CharField(max_length=255)),
                ("sheet_name", models.CharField(default="CRM Export", max_length=120)),
                ("rows_exported", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("completed", "Completed"), ("error", "Error")], db_index=True, default="pending", max_length=30)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sheet_exports", to="integrations.googleintegrationconnection")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("id_company", models.ForeignKey(db_column="id_company", on_delete=django.db.models.deletion.CASCADE, to="companies.company")),
            ],
            options={"db_table": "integration_sheet_export", "ordering": ["-created_at"], "indexes": [models.Index(fields=["id_company", "export_source"], name="int_sheet_company_src_idx")]},
        ),
        migrations.CreateModel(
            name="GoogleAnalyticsSnapshot",
            fields=[
                ("id_snapshot", models.BigAutoField(primary_key=True, serialize=False)),
                ("property_id", models.CharField(max_length=80)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("sessions", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                ("total_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analytics_snapshots", to="integrations.googleintegrationconnection")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("id_company", models.ForeignKey(db_column="id_company", on_delete=django.db.models.deletion.CASCADE, to="companies.company")),
            ],
            options={"db_table": "integration_analytics_snapshot", "ordering": ["-created_at"], "indexes": [models.Index(fields=["id_company", "property_id"], name="int_ga_company_prop_idx")]},
        ),
        migrations.CreateModel(
            name="GoogleAdsSnapshot",
            fields=[
                ("id_snapshot", models.BigAutoField(primary_key=True, serialize=False)),
                ("customer_id", models.CharField(max_length=40)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("conversions", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("campaign_rows", models.JSONField(blank=True, default=list)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ads_snapshots", to="integrations.googleintegrationconnection")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("id_company", models.ForeignKey(db_column="id_company", on_delete=django.db.models.deletion.CASCADE, to="companies.company")),
            ],
            options={"db_table": "integration_ads_snapshot", "ordering": ["-created_at"], "indexes": [models.Index(fields=["id_company", "customer_id"], name="int_ads_company_cust_idx")]},
        ),
    ]
