# Generated by Django 5.2.16 on 2026-07-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_google_ads_leads_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheetexport',
            name='export_source',
            field=models.CharField(choices=[('clients', 'Clients'), ('leads', 'Leads'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('suppliers', 'Suppliers'), ('supplier_purchases', 'Supplier Purchases'), ('analytics', 'Analytics Snapshot'), ('ads', 'Google Ads Snapshot'), ('google_ads_leads', 'Google Ads / LSA Leads')], max_length=60),
        ),
    ]
