SUPPLIER_STATUS_ACTIVE = "active"
SUPPLIER_STATUS_INACTIVE = "inactive"
SUPPLIER_STATUS_BLOCKED = "blocked"

SUPPLIER_STATUS_CHOICES = [
    (SUPPLIER_STATUS_ACTIVE, "Active"),
    (SUPPLIER_STATUS_INACTIVE, "Inactive"),
    (SUPPLIER_STATUS_BLOCKED, "Blocked"),
]

SUPPLIER_TYPE_MATERIALS = "materials"
SUPPLIER_TYPE_SERVICES = "services"
SUPPLIER_TYPE_EQUIPMENT = "equipment"
SUPPLIER_TYPE_TRANSPORTATION = "transportation"
SUPPLIER_TYPE_OFFICE = "office"
SUPPLIER_TYPE_SOFTWARE = "software"
SUPPLIER_TYPE_MARKETING = "marketing"
SUPPLIER_TYPE_OTHER = "other"

SUPPLIER_TYPE_CHOICES = [
    (SUPPLIER_TYPE_MATERIALS, "Materials"),
    (SUPPLIER_TYPE_SERVICES, "Services"),
    (SUPPLIER_TYPE_EQUIPMENT, "Equipment"),
    (SUPPLIER_TYPE_TRANSPORTATION, "Transportation"),
    (SUPPLIER_TYPE_OFFICE, "Office"),
    (SUPPLIER_TYPE_SOFTWARE, "Software"),
    (SUPPLIER_TYPE_MARKETING, "Marketing"),
    (SUPPLIER_TYPE_OTHER, "Other"),
]

OFFER_TYPE_PRODUCT = "product"
OFFER_TYPE_SERVICE = "service"
OFFER_TYPE_MATERIAL = "material"
OFFER_TYPE_EQUIPMENT = "equipment"
OFFER_TYPE_RENTAL = "rental"
OFFER_TYPE_OTHER = "other"

OFFER_TYPE_CHOICES = [
    (OFFER_TYPE_PRODUCT, "Product"),
    (OFFER_TYPE_SERVICE, "Service"),
    (OFFER_TYPE_MATERIAL, "Material"),
    (OFFER_TYPE_EQUIPMENT, "Equipment"),
    (OFFER_TYPE_RENTAL, "Rental"),
    (OFFER_TYPE_OTHER, "Other"),
]

SUPPLIER_CATEGORY_MATERIALS = "materials"
SUPPLIER_CATEGORY_TOOLS = "tools"
SUPPLIER_CATEGORY_EQUIPMENT = "equipment"
SUPPLIER_CATEGORY_LABOR = "labor"
SUPPLIER_CATEGORY_TRANSPORTATION = "transportation"
SUPPLIER_CATEGORY_RENTALS = "rentals"
SUPPLIER_CATEGORY_OFFICE = "office"
SUPPLIER_CATEGORY_SOFTWARE = "software"
SUPPLIER_CATEGORY_MARKETING = "marketing"
SUPPLIER_CATEGORY_OTHER = "other"

SUPPLIER_CATEGORY_CHOICES = [
    (SUPPLIER_CATEGORY_MATERIALS, "Materials"),
    (SUPPLIER_CATEGORY_TOOLS, "Tools"),
    (SUPPLIER_CATEGORY_EQUIPMENT, "Equipment"),
    (SUPPLIER_CATEGORY_LABOR, "Labor"),
    (SUPPLIER_CATEGORY_TRANSPORTATION, "Transportation"),
    (SUPPLIER_CATEGORY_RENTALS, "Rentals"),
    (SUPPLIER_CATEGORY_OFFICE, "Office"),
    (SUPPLIER_CATEGORY_SOFTWARE, "Software"),
    (SUPPLIER_CATEGORY_MARKETING, "Marketing"),
    (SUPPLIER_CATEGORY_OTHER, "Other"),
]

PURCHASE_STATUS_DRAFT = "draft"
PURCHASE_STATUS_PENDING = "pending"
PURCHASE_STATUS_COMPLETED = "completed"
PURCHASE_STATUS_CANCELLED = "cancelled"

PURCHASE_STATUS_CHOICES = [
    (PURCHASE_STATUS_DRAFT, "Draft"),
    (PURCHASE_STATUS_PENDING, "Pending"),
    (PURCHASE_STATUS_COMPLETED, "Completed"),
    (PURCHASE_STATUS_CANCELLED, "Cancelled"),
]

PURCHASE_PAYMENT_STATUS_UNPAID = "unpaid"
PURCHASE_PAYMENT_STATUS_PARTIAL = "partial"
PURCHASE_PAYMENT_STATUS_PAID = "paid"

PURCHASE_PAYMENT_STATUS_CHOICES = [
    (PURCHASE_PAYMENT_STATUS_UNPAID, "Unpaid"),
    (PURCHASE_PAYMENT_STATUS_PARTIAL, "Partially Paid"),
    (PURCHASE_PAYMENT_STATUS_PAID, "Paid"),
]

DOCUMENT_TYPE_RECEIPT = "receipt"
DOCUMENT_TYPE_SUPPLIER_INVOICE = "supplier_invoice"
DOCUMENT_TYPE_QUOTE = "quote"
DOCUMENT_TYPE_CONTRACT = "contract"
DOCUMENT_TYPE_WARRANTY = "warranty"
DOCUMENT_TYPE_OTHER = "other"

DOCUMENT_TYPE_CHOICES = [
    (DOCUMENT_TYPE_RECEIPT, "Receipt"),
    (DOCUMENT_TYPE_SUPPLIER_INVOICE, "Supplier Invoice"),
    (DOCUMENT_TYPE_QUOTE, "Quote"),
    (DOCUMENT_TYPE_CONTRACT, "Contract"),
    (DOCUMENT_TYPE_WARRANTY, "Warranty"),
    (DOCUMENT_TYPE_OTHER, "Other"),
]
