PLATFORM_AUDIT_ACTION_CREATE = "create"
PLATFORM_AUDIT_ACTION_UPDATE = "update"
PLATFORM_AUDIT_ACTION_DELETE = "delete"
PLATFORM_AUDIT_ACTION_ACTIVATE = "activate"
PLATFORM_AUDIT_ACTION_DEACTIVATE = "deactivate"
PLATFORM_AUDIT_ACTION_SUSPEND = "suspend"
PLATFORM_AUDIT_ACTION_RENEW = "renew"
PLATFORM_AUDIT_ACTION_SEND = "send"
PLATFORM_AUDIT_ACTION_EXPORT = "export"
PLATFORM_AUDIT_ACTION_LOGIN = "login"
PLATFORM_AUDIT_ACTION_OTHER = "other"

PLATFORM_AUDIT_ACTION_CHOICES = [
    (PLATFORM_AUDIT_ACTION_CREATE, "Create"),
    (PLATFORM_AUDIT_ACTION_UPDATE, "Update"),
    (PLATFORM_AUDIT_ACTION_DELETE, "Delete"),
    (PLATFORM_AUDIT_ACTION_ACTIVATE, "Activate"),
    (PLATFORM_AUDIT_ACTION_DEACTIVATE, "Deactivate"),
    (PLATFORM_AUDIT_ACTION_SUSPEND, "Suspend"),
    (PLATFORM_AUDIT_ACTION_RENEW, "Renew"),
    (PLATFORM_AUDIT_ACTION_SEND, "Send"),
    (PLATFORM_AUDIT_ACTION_EXPORT, "Export"),
    (PLATFORM_AUDIT_ACTION_LOGIN, "Login"),
    (PLATFORM_AUDIT_ACTION_OTHER, "Other"),
]