# Generated by ChatGPT fix package

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_invoiceitem_invoice_balance_due_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pdf_header_dark",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="invoices/items/"),
        ),
    ]
