SUPERVISION_STATUS_PENDING = "pending"
SUPERVISION_STATUS_APPROVED = "approved"
SUPERVISION_STATUS_FINAL_AUDIT = "final_audit"

SUPERVISION_STATUS_CHOICES = [
    (SUPERVISION_STATUS_PENDING, "Pending"),
    (SUPERVISION_STATUS_APPROVED, "Approved"),
    (SUPERVISION_STATUS_FINAL_AUDIT, "Final Audit"),
]
