PROJECT_STATUS_DRAFT = "draft"
PROJECT_STATUS_PENDING = "pending"
PROJECT_STATUS_IN_PROGRESS = "in_progress"
PROJECT_STATUS_REVIEW = "review"
PROJECT_STATUS_COMPLETED = "completed"
PROJECT_STATUS_CANCELLED = "cancelled"

PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_DRAFT, "Draft"),
    (PROJECT_STATUS_PENDING, "Pending"),
    (PROJECT_STATUS_IN_PROGRESS, "In Progress"),
    (PROJECT_STATUS_REVIEW, "Under Review"),
    (PROJECT_STATUS_COMPLETED, "Approved"),
    (PROJECT_STATUS_CANCELLED, "Void"),
]

PROJECT_MANUAL_STATUS_VALUES = {
    PROJECT_STATUS_DRAFT,
    PROJECT_STATUS_PENDING,
    PROJECT_STATUS_IN_PROGRESS,
}
PROJECT_LOCKED_STATUS_VALUES = {
    PROJECT_STATUS_REVIEW,
    PROJECT_STATUS_COMPLETED,
    PROJECT_STATUS_CANCELLED,
}

ASSIGNMENT_STATUS_ASSIGNED = "assigned"
ASSIGNMENT_STATUS_IN_PROGRESS = "in_progress"
ASSIGNMENT_STATUS_COMPLETED = "completed"
ASSIGNMENT_STATUS_CANCELLED = "cancelled"

ASSIGNMENT_STATUS_CHOICES = [
    (ASSIGNMENT_STATUS_ASSIGNED, "Assigned"),
    (ASSIGNMENT_STATUS_IN_PROGRESS, "In Progress"),
    (ASSIGNMENT_STATUS_COMPLETED, "Completed"),
    (ASSIGNMENT_STATUS_CANCELLED, "Cancelled"),
]
