# Generated by Django 5.2.14 on 2026-05-19 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('id_invoice', models.ForeignKey(db_column='id_invoice', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
                ('id_project', models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='projects.project')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-payment_date', '-id_payment'],
            },
        ),
    ]
