# Generated by Django 5.2.15 on 2026-06-10 21:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_code_client_first_name_and_more'),
        ('companies', '0006_remove_company_website'),
        ('invoices', '0002_invoiceitem_invoice_balance_due_and_more'),
        ('payments', '0002_payment_notes_payment_receipt_file_and_more'),
        ('projects', '0002_projectevidence_projectgalleryimage_projectnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCreditAccount',
            fields=[
                ('id_credit_account', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'client_credit_account',
                'ordering': ['id_client'],
            },
        ),
        migrations.CreateModel(
            name='ClientCreditMovement',
            fields=[
                ('id_credit_movement', models.BigAutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('created', 'Credit Created'), ('applied', 'Credit Applied'), ('voided', 'Credit Voided'), ('adjustment', 'Credit Adjustment')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('movement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'client_credit_movement',
                'ordering': ['-movement_date', '-id_credit_movement'],
            },
        ),
        migrations.CreateModel(
            name='FinancialMovement',
            fields=[
                ('id_financial_movement', models.BigAutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('void', 'Invoice Void'), ('payment_void', 'Payment Void'), ('credit_created', 'Credit Created'), ('credit_applied', 'Credit Applied'), ('credit_void', 'Credit Void')], max_length=50)),
                ('movement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount that increases client debt.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount that reduces client debt.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'financial_movement',
                'ordering': ['-movement_date', '-id_financial_movement'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id_payment_allocation', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('allocated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'payment_allocation',
                'ordering': ['id_payment_allocation'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='id_client',
            field=models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='id_company',
            field=models.ForeignKey(blank=True, db_column='id_company', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='companies.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_code',
            field=models.CharField(blank=True, help_text='Receipt, check, bank transfer, Zelle, ACH or external confirmation code.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id_invoice',
            field=models.ForeignKey(blank=True, db_column='id_invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('zelle', 'Zelle'), ('ach', 'ACH'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('other', 'Other')], default='cash', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('verified', 'Verified'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('void', 'Void')], default='pending_payment', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_number__isnull', False), models.Q(('payment_number', ''), _negated=True)), fields=('id_company', 'payment_number'), name='unique_payment_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('voucher_code__isnull', False), models.Q(('voucher_code', ''), _negated=True), models.Q(('status', 'void'), _negated=True)), fields=('id_company', 'voucher_code'), name='unique_active_payment_voucher_per_company'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_code__isnull', False), models.Q(('reference_code', ''), _negated=True), models.Q(('status', 'void'), _negated=True)), fields=('id_company', 'reference_code'), name='unique_active_payment_reference_per_company'),
        ),
        migrations.AddField(
            model_name='clientcreditaccount',
            name='id_client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.PROTECT, related_name='credit_accounts', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientcreditaccount',
            name='id_company',
            field=models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.PROTECT, related_name='client_credit_accounts', to='companies.company'),
        ),
        migrations.AddField(
            model_name='clientcreditmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientcreditmovement',
            name='id_client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.PROTECT, related_name='credit_movements', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientcreditmovement',
            name='id_company',
            field=models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.PROTECT, related_name='client_credit_movements', to='companies.company'),
        ),
        migrations.AddField(
            model_name='clientcreditmovement',
            name='id_invoice',
            field=models.ForeignKey(blank=True, db_column='id_invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_movements', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='clientcreditmovement',
            name='id_payment',
            field=models.ForeignKey(blank=True, db_column='id_payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_movements', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='id_client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='clients.client'),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='id_company',
            field=models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='companies.company'),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='id_invoice',
            field=models.ForeignKey(blank=True, db_column='id_invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='id_payment',
            field=models.ForeignKey(blank=True, db_column='id_payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='projects.project'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='id_client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='clients.client'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='id_company',
            field=models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='companies.company'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='id_invoice',
            field=models.ForeignKey(db_column='id_invoice', on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='id_payment',
            field=models.ForeignKey(db_column='id_payment', on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocations', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='clientcreditaccount',
            constraint=models.UniqueConstraint(fields=('id_company', 'id_client'), name='unique_credit_account_per_company_client'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('id_payment', 'id_invoice'), name='unique_invoice_allocation_per_payment'),
        ),
    ]
