NOTIFICATION_STATUS_UNREAD = "unread"
NOTIFICATION_STATUS_READ = "read"
NOTIFICATION_STATUS_ARCHIVED = "archived"

NOTIFICATION_STATUS_CHOICES = [
    (NOTIFICATION_STATUS_UNREAD, "Unread"),
    (NOTIFICATION_STATUS_READ, "Read"),
    (NOTIFICATION_STATUS_ARCHIVED, "Archived"),
]

NOTIFICATION_TYPE_SYSTEM = "system"
NOTIFICATION_TYPE_TASK = "task"
NOTIFICATION_TYPE_PROJECT = "project"
NOTIFICATION_TYPE_INSPECTION = "inspection"
NOTIFICATION_TYPE_BILLING = "billing"
NOTIFICATION_TYPE_CONTRACT = "contract"

NOTIFICATION_TYPE_CHOICES = [
    (NOTIFICATION_TYPE_SYSTEM, "System"),
    (NOTIFICATION_TYPE_TASK, "Task"),
    (NOTIFICATION_TYPE_PROJECT, "Project"),
    (NOTIFICATION_TYPE_INSPECTION, "Inspection"),
    (NOTIFICATION_TYPE_BILLING, "Billing"),
    (NOTIFICATION_TYPE_CONTRACT, "Contract"),
]