# Generated by Django 5.2.15 on 2026-06-10 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_client_code_client_first_name_and_more'),
        ('companies', '0006_remove_company_website'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id_lead', models.BigAutoField(primary_key=True, serialize=False)),
                ('opportunity_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('second_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('website', 'Website'), ('phone', 'Phone'), ('email', 'Email'), ('referral', 'Referral'), ('social', 'Social Media'), ('other', 'Other')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('won', 'Won'), ('converted', 'Converted'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='new', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('approximate_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_assigned_user', models.ForeignKey(blank=True, db_column='id_assigned_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL)),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='clients.client')),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='companies.company')),
                ('id_converted_project', models.ForeignKey(blank=True, db_column='id_converted_project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_opportunities', to='projects.project')),
            ],
            options={
                'db_table': 'opportunity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityFollowUp',
            fields=[
                ('id_follow_up', models.BigAutoField(primary_key=True, serialize=False)),
                ('follow_up_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('text', 'Text Message'), ('visit', 'Visit'), ('note', 'Note')], default='call', max_length=50)),
                ('note', models.TextField()),
                ('follow_up_date', models.DateTimeField(auto_now_add=True)),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('id_opportunity', models.ForeignKey(db_column='id_opportunity', on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='opportunities.lead')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opportunity_follow_up',
                'ordering': ['-follow_up_date'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['id_company', 'status'], name='opportunity_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['opportunity_code'], name='opportunity_code_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='opportunity_created_idx'),
        ),
    ]
