# Generated by Django 5.2.15 on 2026-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('phone', 'Phone'), ('email', 'Email'), ('referral', 'Referral'), ('social', 'Social Media'), ('local_services_ads', 'Local Services Ads'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('won', 'Won'), ('cancelled', 'Cancelled'), ('converted', 'Converted')], default='new', max_length=50),
        ),
    ]
