# Generated by Django 5.2.14 on 2026-05-27 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_remove_company_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id_audit', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('suspend', 'Suspend'), ('renew', 'Renew'), ('send', 'Send'), ('export', 'Export'), ('login', 'Login'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('object_label', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, db_column='actor_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('id_company', models.ForeignKey(blank=True, db_column='id_company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_logs', to='companies.company')),
            ],
            options={
                'db_table': 'platform_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module_name'], name='platform_audit_module_idx'), models.Index(fields=['action'], name='platform_audit_action_idx'), models.Index(fields=['created_at'], name='platform_audit_created_idx'), models.Index(fields=['object_id'], name='platform_audit_object_idx')],
            },
        ),
    ]
