# Generated by Django 5.2.14 on 2026-05-19 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id_contract', models.BigAutoField(primary_key=True, serialize=False)),
                ('terms', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
                ('id_project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project')),
            ],
            options={
                'db_table': 'contract',
                'ordering': ['-id_contract'],
            },
        ),
    ]
