# Generated by ChatGPT fix package

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_additional_work_contract_balance_due_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="pdf_header_dark",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="project_photo",
            field=models.ImageField(blank=True, null=True, upload_to="contracts/projects/"),
        ),
    ]
