# Generated by Django 5.2.15 on 2026-06-16 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_updated_at'),
        ('companies', '0006_remove_company_website'),
        ('contracts', '0003_contract_pdf_header_dark_project_photo'),
        ('estimates', '0003_estimate_pdf_header_dark_estimateitem_photo'),
        ('projects', '0004_project_project_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='id_estimate',
            field=models.ForeignKey(blank=True, db_column='id_estimate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='estimates.estimate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='sign_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='sign_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='sign_token_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/signatures/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/signed/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='terms_summary',
            field=models.TextField(blank=True, default='This contract includes the basic terms and conditions for the project. For complete terms and conditions, please review the company terms page.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='terms_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('approved', 'Approved'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('void', 'Void'), ('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['id_company', 'id_estimate'], name='contract_id_comp_fdbb30_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['public_token'], name='contract_public__9d9cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['sign_token'], name='contract_sign_to_62491d_idx'),
        ),
    ]
