# Generated by Django 5.2.15 on 2026-06-16 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_approved_at_contract_id_estimate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sign_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
