# Generated by Django 5.2.15 on 2026-06-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_public_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEvidence',
            fields=[
                ('id_contract_evidence', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='contracts/evidence/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_contract', models.ForeignKey(db_column='id_contract', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_photos', to='contracts.contract')),
            ],
            options={
                'db_table': 'contract_evidence',
                'ordering': ['sort_order', 'id_contract_evidence'],
            },
        ),
    ]
