# Generated by Django 5.2.15 on 2026-06-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cancellation_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='guarantee_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='miscellaneous_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_terms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
