EVIDENCE_TYPE_PROJECT_PHOTO = "project_photo"
EVIDENCE_TYPE_INSPECTION_PHOTO = "inspection_photo"
EVIDENCE_TYPE_BEFORE_PHOTO = "before_photo"
EVIDENCE_TYPE_AFTER_PHOTO = "after_photo"
EVIDENCE_TYPE_DOCUMENT = "document"
EVIDENCE_TYPE_CONTRACT = "contract"
EVIDENCE_TYPE_INVOICE = "invoice"
EVIDENCE_TYPE_PAYMENT = "payment"
EVIDENCE_TYPE_OTHER = "other"

EVIDENCE_TYPE_CHOICES = [
    (EVIDENCE_TYPE_PROJECT_PHOTO, "Project Photo"),
    (EVIDENCE_TYPE_INSPECTION_PHOTO, "Inspection Photo"),
    (EVIDENCE_TYPE_BEFORE_PHOTO, "Before Photo"),
    (EVIDENCE_TYPE_AFTER_PHOTO, "After Photo"),
    (EVIDENCE_TYPE_DOCUMENT, "Document"),
    (EVIDENCE_TYPE_CONTRACT, "Contract"),
    (EVIDENCE_TYPE_INVOICE, "Invoice"),
    (EVIDENCE_TYPE_PAYMENT, "Payment"),
    (EVIDENCE_TYPE_OTHER, "Other"),
]
