ESTIMATE_STATUS_DRAFT = "draft"

ESTIMATE_STATUS_PENDING = "pending"
ESTIMATE_STATUS_PENDING_SEND = "pending_send"

ESTIMATE_STATUS_SENT = "sent"
ESTIMATE_STATUS_VIEWED = "viewed"
ESTIMATE_STATUS_APPROVED = "approved"
ESTIMATE_STATUS_REJECTED = "rejected"
ESTIMATE_STATUS_EXPIRED = "expired"
ESTIMATE_STATUS_CONVERTED = "converted"
ESTIMATE_STATUS_CANCELLED = "cancelled"


ESTIMATE_STATUS_CHOICES = [
    (ESTIMATE_STATUS_DRAFT, "Draft"),
    (ESTIMATE_STATUS_PENDING, "Pending"),
    (ESTIMATE_STATUS_PENDING_SEND, "Pending Send"),
    (ESTIMATE_STATUS_SENT, "Sent"),
    (ESTIMATE_STATUS_VIEWED, "Viewed"),
    (ESTIMATE_STATUS_APPROVED, "Approved"),
    (ESTIMATE_STATUS_REJECTED, "Rejected"),
    (ESTIMATE_STATUS_EXPIRED, "Expired"),
    (ESTIMATE_STATUS_CONVERTED, "Converted"),
    (ESTIMATE_STATUS_CANCELLED, "Cancelled"),
]


ESTIMATE_PROTECTED_STATUSES = [
    ESTIMATE_STATUS_APPROVED,
    ESTIMATE_STATUS_CONVERTED,
    ESTIMATE_STATUS_CANCELLED,
]

ESTIMATE_CLOSED_STATUSES = [
    ESTIMATE_STATUS_REJECTED,
    ESTIMATE_STATUS_CONVERTED,
    ESTIMATE_STATUS_CANCELLED,
]

ESTIMATE_EDIT_ALLOWED_STATUSES = [
    ESTIMATE_STATUS_DRAFT,
    ESTIMATE_STATUS_PENDING,
    ESTIMATE_STATUS_PENDING_SEND,
    ESTIMATE_STATUS_SENT,
    ESTIMATE_STATUS_VIEWED,
    ESTIMATE_STATUS_REJECTED,
    ESTIMATE_STATUS_EXPIRED,
]

ESTIMATE_SEND_ALLOWED_STATUSES = [
    ESTIMATE_STATUS_PENDING,
    ESTIMATE_STATUS_PENDING_SEND,
    ESTIMATE_STATUS_SENT,
    ESTIMATE_STATUS_VIEWED,
    ESTIMATE_STATUS_REJECTED,
]

ESTIMATE_DECISION_ALLOWED_STATUSES = [
    ESTIMATE_STATUS_SENT,
    ESTIMATE_STATUS_VIEWED,
]

ESTIMATE_CONVERT_ALLOWED_STATUSES = [
    ESTIMATE_STATUS_APPROVED,
]