# Generated by Django 5.2.14 on 2026-05-26 21:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_slug_company_company_slug_idx'),
        ('platform_subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDocument',
            fields=[
                ('id_document', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_number', models.CharField(db_index=True, max_length=80, unique=True)),
                ('document_type', models.CharField(choices=[('proforma', 'Proforma'), ('invoice', 'Invoice')], db_index=True, default='proforma', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('void', 'Void'), ('overdue', 'Overdue')], db_index=True, default='draft', max_length=30)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_documents', to=settings.AUTH_USER_MODEL)),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='platform_documents', to='companies.company')),
                ('id_subscription', models.ForeignKey(blank=True, db_column='id_subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_documents', to='platform_subscriptions.platformsubscription')),
            ],
            options={
                'db_table': 'platform_document',
                'ordering': ['-issue_date', '-id_document'],
            },
        ),
        migrations.CreateModel(
            name='PlatformDocumentItem',
            fields=[
                ('id_document_item', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('id_document', models.ForeignKey(db_column='id_document', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='platform_documents.platformdocument')),
            ],
            options={
                'db_table': 'platform_document_item',
                'ordering': ['id_document_item'],
            },
        ),
        migrations.AddIndex(
            model_name='platformdocument',
            index=models.Index(fields=['document_type'], name='platform_doc_type_idx'),
        ),
        migrations.AddIndex(
            model_name='platformdocument',
            index=models.Index(fields=['status'], name='platform_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='platformdocument',
            index=models.Index(fields=['issue_date'], name='platform_doc_issue_idx'),
        ),
        migrations.AddIndex(
            model_name='platformdocument',
            index=models.Index(fields=['due_date'], name='platform_doc_due_idx'),
        ),
    ]
