# Generated by Django 5.2.14 on 2026-05-27 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformdocument',
            name='source_document',
            field=models.ForeignKey(blank=True, db_column='source_document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='platform_documents.platformdocument'),
        ),
    ]
