# Generated by Django 5.2.14 on 2026-05-27 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_remove_company_website'),
        ('platform_subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformNotificationLog',
            fields=[
                ('id_notification', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('renewal_reminder', 'Renewal Reminder'), ('subscription_expired', 'Subscription Expired'), ('payment_registered', 'Payment Registered'), ('document_sent', 'Document Sent'), ('company_suspended', 'Company Suspended'), ('manual', 'Manual')], db_index=True, default='renewal_reminder', max_length=60)),
                ('channel', models.CharField(choices=[('email', 'Email')], db_index=True, default='email', max_length=30)),
                ('recipient_email', models.EmailField(max_length=180)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_notifications', to=settings.AUTH_USER_MODEL)),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='platform_notification_logs', to='companies.company')),
                ('id_subscription', models.ForeignKey(blank=True, db_column='id_subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_notification_logs', to='platform_subscriptions.platformsubscription')),
            ],
            options={
                'db_table': 'platform_notification_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_type'], name='platform_notif_type_idx'), models.Index(fields=['channel'], name='platform_notif_channel_idx'), models.Index(fields=['status'], name='platform_notif_status_idx'), models.Index(fields=['created_at'], name='platform_notif_created_idx')],
            },
        ),
    ]
